# Copyright (c) 2022 Rockchip Electronics Co. Ltd.
# Author: Xing Zheng <zhengxing@rock-chips.com>

pcm.!default
{
    type asym
    playback.pcm "plug:multi_ply2"
    capture.pcm "plug:multi_cap2"
}

pcm.mix_ply2 {
    type route
    slave {
        pcm multi_ply
        channels 2
    }
    ttable {
        0.0 1.0
        1.0 1.0
        0.1 1.0
        1.1 1.0
    }
}

pcm.dmixer {
    type dmix
    ipc_key 5978293 # must be unique for all dmix plugins!!!!
    ipc_key_add_uid yes
    slave {
        pcm "hw:0,0"
        channels 2
        period_size 2048
        buffer_size 8192
    }
    bindings {
        0 0
        1 1
    }
}

pcm.dsnooper {
    type dsnoop
    ipc_key 5978294 # must be unique for all dmix plugins!!!!
    ipc_key_add_uid yes
    slave {
        pcm "hw:0,0"
        channels 2
        period_size 2048
        buffer_size 8192
    }
    bindings {
        0 0
        1 1
    }
}

pcm.softvol_ply {
    type softvol
    slave.pcm "dmixer"
    control {
        name "Master Playback Volume"
        card 0
        device 0
    }
    min_dB -40.0
    max_dB 0.0
    resolution 101
}

pcm.softvol_cap {
    type softvol
     slave.pcm "dsnooper"
    control {
        name "Master Capture Volume"
        card 0
        device 0
    }
    min_dB -40.0
    max_dB 0.0
    resolution 101
}

pcm.multi_ply2 {
    type multi
    slaves.a.pcm "hw:0,0,0"
    slaves.b.pcm "hw:7,0,0"
    slaves.a.channels 2
    slaves.b.channels 2
    bindings.0.slave a
    bindings.0.channel 0 # Codec Left Channel
    bindings.1.slave b
    bindings.1.channel 0 # ALOOP Left Channel
}

pcm.multi_cap2 {
    type multi
    slaves.a.pcm "hw:0,0,0"
    slaves.b.pcm "hw:7,1,0"
    slaves.a.channels 2
    slaves.b.channels 2
    bindings.0.slave a
    bindings.0.channel 0 # Codec Left Channel
    bindings.1.slave b
    bindings.1.channel 0 # ALOOP Left Channel
}





