#!/bin/sh

case "$1" in
  start)
    echo "Starting guard..."
    export LD_LIBRARY_PATH=/oem/usr/lib:$LD_LIBRARY_PATH
    /oem/usr/bin/guard &
    ;;
  stop)
    echo "Stopping guard..."
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0