	.arch armv7-a
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 4
	.eabi_attribute 34, 1
	.eabi_attribute 18, 2
	.file	"mpi_dev.c"
	.text
	.syntax unified
	.syntax unified
	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_in_watcher:					
	.asciz 	"mpi_node_add_in_watcher"					
__kstrtabns_mpi_node_add_in_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_in_filter:					
	.asciz 	"mpi_node_add_in_filter"					
__kstrtabns_mpi_node_add_in_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_out_watcher:					
	.asciz 	"mpi_node_add_out_watcher"					
__kstrtabns_mpi_node_add_out_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_add_out_filter:					
	.asciz 	"mpi_node_add_out_filter"					
__kstrtabns_mpi_node_add_out_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_in_watcher:					
	.asciz 	"mpi_node_del_in_watcher"					
__kstrtabns_mpi_node_del_in_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_in_filter:					
	.asciz 	"mpi_node_del_in_filter"					
__kstrtabns_mpi_node_del_in_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_out_watcher:					
	.asciz 	"mpi_node_del_out_watcher"					
__kstrtabns_mpi_node_del_out_watcher:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_del_out_filter:					
	.asciz 	"mpi_node_del_out_filter"					
__kstrtabns_mpi_node_del_out_filter:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_enable_auto_streamon:					
	.asciz 	"mpi_node_enable_auto_streamon"					
__kstrtabns_mpi_node_enable_auto_streamon:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_pick_in_buffer:					
	.asciz 	"mpi_node_pick_in_buffer"					
__kstrtabns_mpi_node_pick_in_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_pick_out_buffer:					
	.asciz 	"mpi_node_pick_out_buffer"					
__kstrtabns_mpi_node_pick_out_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_release_buffer_flag:					
	.asciz 	"mpi_node_release_buffer_flag"					
__kstrtabns_mpi_node_release_buffer_flag:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_set_frame_rate:					
	.asciz 	"mpi_node_set_frame_rate"					
__kstrtabns_mpi_node_set_frame_rate:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_force_lost_frame:					
	.asciz 	"mpi_node_force_lost_frame"					
__kstrtabns_mpi_node_force_lost_frame:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_streamon:					
	.asciz 	"mpi_node_streamon"					
__kstrtabns_mpi_node_streamon:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_streamoff:					
	.asciz 	"mpi_node_streamoff"					
__kstrtabns_mpi_node_streamoff:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_stream_pause:					
	.asciz 	"mpi_node_stream_pause"					
__kstrtabns_mpi_node_stream_pause:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_buffer_in:					
	.asciz 	"mpi_node_buffer_in"					
__kstrtabns_mpi_node_buffer_in:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_buffer_out:					
	.asciz 	"mpi_node_buffer_out"					
__kstrtabns_mpi_node_buffer_out:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_get_in_buffer:					
	.asciz 	"mpi_node_get_in_buffer"					
__kstrtabns_mpi_node_get_in_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_get_out_buffer:					
	.asciz 	"mpi_node_get_out_buffer"					
__kstrtabns_mpi_node_get_out_buffer:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_request_buf:					
	.asciz 	"mpi_node_request_buf"					
__kstrtabns_mpi_node_request_buf:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_flush:					
	.asciz 	"mpi_node_flush"					
__kstrtabns_mpi_node_flush:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_unbind:					
	.asciz 	"mpi_node_unbind"					
__kstrtabns_mpi_node_unbind:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_bind:					
	.asciz 	"mpi_node_bind"					
__kstrtabns_mpi_node_bind:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_set_params:					
	.asciz 	"mpi_node_set_params"					
__kstrtabns_mpi_node_set_params:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_node_destroy:					
	.asciz 	"mpi_node_destroy"					
__kstrtabns_mpi_node_destroy:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_create_node_with_params:					
	.asciz 	"mpi_dev_create_node_with_params"					
__kstrtabns_mpi_dev_create_node_with_params:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_request_job:					
	.asciz 	"mpi_dev_request_job"					
__kstrtabns_mpi_dev_request_job:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_request_job_for_node:					
	.asciz 	"mpi_dev_request_job_for_node"					
__kstrtabns_mpi_dev_request_job_for_node:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_run_job:					
	.asciz 	"mpi_dev_run_job"					
__kstrtabns_mpi_dev_run_job:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_unregister:					
	.asciz 	"mpi_dev_unregister"					
__kstrtabns_mpi_dev_unregister:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_mpi_dev_register:					
	.asciz 	"mpi_dev_register"					
__kstrtabns_mpi_dev_register:					
	.asciz 	""					
	.previous						

	.thumb
	.syntax unified
	.align	1
	.global	mpi_node_force_lost_frame
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_force_lost_frame, %function
mpi_node_force_lost_frame:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	bic	r1, r1, r1, asr #31
	str	r1, [r0]
	movs	r0, #0
	bx	lr
	.fnend
	.size	mpi_node_force_lost_frame, .-mpi_node_force_lost_frame
	.align	1
	.global	mpi_node_streamon
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_streamon, %function
mpi_node_streamon:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	ldr	r3, [r0, #40]
	ldr	r6, [r0, #80]
	tst	r3, #3072
	bne	.L9
	cbz	r0, .L4
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L5
.L4:
.L9:
	mov	r5, #-1
	b	.L2
.L5:
	bl	mpi_obj_ref
	ldr	r5, [r4, #40]
	ands	r5, r5, #4096
	beq	.L6
.L8:
	movs	r5, #0
.L7:
	mov	r0, r4
	bl	mpi_obj_unref
.L2:
	mov	r0, r5
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L6:
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L16
	mov	r0, r5
	str	r3, [sp, #8]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	mov	r3, #410
	str	r3, [sp]
	ldr	r3, .L16+4
	bl	vlog
	ldr	r3, [r6, #116]
	cmp	r3, #0
	beq	.L8
	mov	r2, r5
	movs	r1, #5
	mov	r0, r4
	blx	r3
	mov	r5, r0
	cmp	r0, #0
	bne	.L7
	ldr	r3, [r4, #40]
	orr	r3, r3, #4096
	str	r3, [r4, #40]
	b	.L7
.L17:
	.align	2
.L16:
	.word	.LC0
	.word	.LANCHOR0
	.fnend
	.size	mpi_node_streamon, .-mpi_node_streamon
	.align	1
	.global	mpi_node_stream_pause
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_stream_pause, %function
mpi_node_stream_pause:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, lr}
	.save {r4, lr}
	mov	r4, r0
	cbz	r0, .L19
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L20
.L19:
	mov	r0, #-1
.L18:
	pop	{r4, pc}
.L20:
.L22:
	bl	mpi_obj_ref
	ldr	r3, [r4, #40]
	mov	r0, r4
	lsls	r2, r3, #19
	itt	mi
	bicmi	r3, r3, #4096
	strmi	r3, [r4, #40]
	bl	mpi_obj_unref
	movs	r0, #0
	b	.L18
	.fnend
	.size	mpi_node_stream_pause, .-mpi_node_stream_pause
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_cleanup_in_buffer, %function
mpi_node_cleanup_in_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	mov	r4, r0
	cbnz	r1, .L30
	ldr	r3, [r0, #352]
	cbnz	r3, .L29
.L30:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r0, [r4, #376]
	cbz	r0, .L32
	movs	r1, #0
	bl	mpi_queue_destroy
	movs	r3, #0
	str	r3, [r4, #376]
.L32:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L29:
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_cleanup_in_buffer, .-mpi_node_cleanup_in_buffer
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_cleanup_out_buffer, %function
mpi_node_cleanup_out_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	mov	r4, r0
	cbnz	r1, .L37
	ldr	r3, [r0, #364]
	cbnz	r3, .L36
.L37:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r0, [r4, #380]
	cbz	r0, .L39
	movs	r1, #0
	bl	mpi_queue_destroy
	movs	r3, #0
	str	r3, [r4, #380]
.L39:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L36:
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_cleanup_out_buffer, .-mpi_node_cleanup_out_buffer
	.align	1
	.global	mpi_node_streamoff
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_streamoff, %function
mpi_node_streamoff:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	mov	r4, r0
	.pad #20
	sub	sp, sp, #20
	ldr	r5, [r0, #80]
	cbz	r0, .L44
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L45
.L44:
	mov	r0, #-1
.L43:
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, pc}
.L45:
	bl	mpi_obj_ref
	ldr	r3, [r4, #40]
	lsls	r3, r3, #19
	bpl	.L47
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L68
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	mov	r3, #442
	str	r3, [sp]
	ldr	r3, .L68+4
	bl	vlog
	ldr	r3, [r4, #40]
	bic	r3, r3, #4096
	str	r3, [r4, #40]
	ldr	r3, [r5, #116]
	cbz	r3, .L48
	movs	r2, #0
	movs	r1, #6
	mov	r0, r4
	blx	r3
.L48:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #352]
	cbnz	r3, .L49
.L53:
	ldr	r3, [r4, #364]
	cbnz	r3, .L51
.L50:
	add	r0, r4, #384
	bl	complete_all
	add	r0, r4, #396
	bl	complete_all
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L47:
	mov	r0, r4
	bl	mpi_obj_unref
	movs	r0, #0
	b	.L43
.L52:
	bl	mpi_obj_unref
	ldr	r3, [r4, #424]
	subs	r3, r3, #1
	str	r3, [r4, #424]
.L49:
	ldr	r0, [r4, #376]
	bl	mpi_queue_pop_obj
	cmp	r0, #0
	bne	.L52
	b	.L53
.L54:
	bl	mpi_obj_unref
	ldr	r3, [r4, #428]
	subs	r3, r3, #1
	str	r3, [r4, #428]
.L51:
	ldr	r0, [r4, #380]
	bl	mpi_queue_pop_obj
	cmp	r0, #0
	bne	.L54
	b	.L50
.L69:
	.align	2
.L68:
	.word	.LC1
	.word	.LANCHOR0+18
	.fnend
	.size	mpi_node_streamoff, .-mpi_node_streamoff
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	count_frame_rate, %function
count_frame_rate:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, r8, lr}
	.save {r4, r5, r6, r7, r8, lr}
	mov	r4, r0
	mov	r7, r1
	mov	r8, r2
	bl	rkos_getjiffies
	mov	r5, r0
	mov	r6, r1
	cmp	r8, #0
	beq	.L71
	ldr	r3, [r4, #164]
	adds	r3, r3, #1
	str	r3, [r4, #164]
	ldr	r3, [r4, #168]
	adds	r3, r3, #1
	str	r3, [r4, #168]
	cbz	r7, .L72
	ldr	r3, [r4, #172]
	adds	r3, r3, #1
	str	r3, [r4, #172]
.L72:
	ldrd	r2, r3, [r4, #184]
	mov	r0, r5
	mov	r1, r6
	adds	r2, r2, #100
	adc	r3, r3, #0
	bl	rkos_time_after
	orrs	r3, r0, r1
	beq	.L70
	ldr	r3, [r4, #168]
	strd	r5, r6, [r4, #184]
	subs	r3, r3, #1
	str	r3, [r4, #176]
	movs	r3, #0
	str	r3, [r4, #168]
.L70:
	pop	{r4, r5, r6, r7, r8, pc}
.L71:
	ldr	r3, [r4, #232]
	adds	r3, r3, #1
	str	r3, [r4, #232]
	ldr	r3, [r4, #236]
	adds	r3, r3, #1
	str	r3, [r4, #236]
	cbz	r7, .L75
	ldr	r3, [r4, #240]
	adds	r3, r3, #1
	str	r3, [r4, #240]
.L75:
	ldr	r2, [r4, #248]
	movs	r7, #0
	mov	r3, r7
	mov	r0, r5
	adds	r2, r2, #100
	mov	r1, r6
	bl	rkos_time_after
	orrs	r3, r0, r1
	beq	.L70
	ldr	r3, [r4, #236]
	str	r5, [r4, #248]
	subs	r3, r3, #1
	str	r7, [r4, #236]
	str	r3, [r4, #244]
	b	.L70
	.fnend
	.size	count_frame_rate, .-count_frame_rate
	.align	1
	.global	mpi_node_flush
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_flush, %function
mpi_node_flush:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #20
	sub	sp, sp, #20
	mov	r5, r1
	ldr	r7, [r0, #80]
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r2, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r0, #40]
	add	r6, r0, #340
	ands	r1, r3, #2048
	beq	.L87
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	mov	r0, r6
	bl	wait_for_completion
.L88:
	movs	r0, #0
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L87:
	orr	r3, r3, #2048
	str	r1, [r0, #340]
	str	r3, [r0, #40]
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r0, #40]
	lsls	r3, r3, #19
	bpl	.L89
	bl	mpi_node_streamoff
.L89:
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L103
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r7, #80]
	str	r3, [sp, #4]
	mov	r3, #836
	str	r3, [sp]
	ldr	r3, .L103+4
	bl	vlog
	ldr	r0, [r4, #336]
	cbz	r0, .L90
	movs	r2, #0
	mov	r1, r5
	bl	mpi_queue_flush
.L90:
	ldr	r3, [r7, #116]
	cbz	r3, .L91
	cbz	r5, .L92
	movs	r2, #0
	movs	r1, #3
.L102:
	mov	r0, r4
	blx	r3
.L91:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	mov	r0, r6
	bl	complete_all
	ldr	r3, [r4, #40]
	bic	r3, r3, #2048
	str	r3, [r4, #40]
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L88
.L92:
	mov	r2, r5
	movs	r1, #2
	b	.L102
.L104:
	.align	2
.L103:
	.word	.LC2
	.word	.LANCHOR0+37
	.fnend
	.size	mpi_node_flush, .-mpi_node_flush
	.align	1
	.global	mpi_node_unbind
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_unbind, %function
mpi_node_unbind:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	.pad #28
	sub	sp, sp, #28
	ldr	r3, [r1]
	mov	r4, r1
	ldr	r2, .L114
	mov	r5, r0
	str	r3, [sp, #16]
	ldr	r3, [r1, #80]
	movs	r1, #5
	ldr	r3, [r3, #80]
	str	r3, [sp, #12]
	ldr	r3, [r0]
	str	r3, [sp, #8]
	ldr	r3, [r0, #80]
	movs	r0, #0
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movw	r3, #887
	str	r3, [sp]
	ldr	r3, .L114+4
	bl	vlog
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_flush
	mov	r0, r4
	bl	mpi_node_streamoff
	ldr	r3, [r4, #40]
	lsls	r2, r3, #18
	bpl	.L105
	bic	r3, r3, #8192
	str	r3, [r4, #40]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #108]
	cbz	r3, .L108
	movs	r1, #0
	ldr	r0, [r4, #316]
	blx	r3
	str	r0, [r4, #316]
.L108:
	mov	r1, r4
	add	r0, r5, #328
	bl	mpi_list_del_obj_rcu
	cbnz	r0, .L109
	mov	r0, r4
	bl	mpi_obj_unref
.L109:
	mov	r1, r5
	add	r0, r4, #320
	bl	mpi_list_del_obj_rcu
	cbnz	r0, .L105
	mov	r0, r5
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, lr}
	b	mpi_obj_unref
.L105:
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, pc}
.L115:
	.align	2
.L114:
	.word	.LC3
	.word	.LANCHOR0+52
	.fnend
	.size	mpi_node_unbind, .-mpi_node_unbind
	.align	1
	.global	mpi_node_bind
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_bind, %function
mpi_node_bind:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	mov	r5, r0
	.pad #24
	sub	sp, sp, #24
	mov	r4, r1
	cbz	r0, .L117
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L118
.L117:
	mov	r6, #-1
.L116:
	mov	r0, r6
	add	sp, sp, #24
	@ sp needed
	pop	{r4, r5, r6, pc}
.L118:
	bl	mpi_obj_ref
	cbz	r4, .L120
	ldr	r3, [r4, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L121
.L120:
	mov	r6, #-1
.L122:
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L116
.L121:
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r3, [r5, #40]
	lsls	r2, r3, #21
	bmi	.L127
	ldr	r3, [r4, #40]
	tst	r3, #9216
	bne	.L127
	mov	r1, r4
	add	r0, r5, #328
	bl	mpi_list_add_tail_obj_rcu
	mov	r0, r5
	bl	mpi_obj_ref
	mov	r1, r5
	add	r0, r4, #320
	bl	mpi_list_add_tail_obj_rcu
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r3, [r4, #40]
	orr	r3, r3, #8192
	str	r3, [r4, #40]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #108]
	cbz	r3, .L124
	mov	r1, r5
	ldr	r0, [r4, #316]
	blx	r3
	str	r0, [r4, #316]
.L124:
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L141
	movs	r0, #0
	str	r3, [sp, #16]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #12]
	ldr	r3, [r5]
	str	r3, [sp, #8]
	ldr	r3, [r5, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movw	r3, #950
	str	r3, [sp]
	ldr	r3, .L141+4
	bl	vlog
	ldr	r3, [r4, #40]
	lsls	r3, r3, #17
	bpl	.L125
	mov	r0, r4
	bl	mpi_node_streamon
.L125:
	ldr	r6, [r5, #40]
	ands	r6, r6, #16384
	beq	.L123
	mov	r0, r5
	movs	r6, #0
	bl	mpi_node_streamon
.L123:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L122
.L127:
	mov	r6, #-1
	b	.L123
.L142:
	.align	2
.L141:
	.word	.LC4
	.word	.LANCHOR0+68
	.fnend
	.size	mpi_node_bind, .-mpi_node_bind
	.align	1
	.global	mpi_node_set_params
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_set_params, %function
mpi_node_set_params:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #8
	mov	r5, r0
	mov	r6, r1
	cbz	r0, .L144
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L145
.L144:
	mov	r4, #-1
.L143:
	mov	r0, r4
	add	sp, sp, #8
	@ sp needed
	pop	{r4, r5, r6, pc}
.L145:
	bl	mpi_obj_ref
	ldr	r4, [r5, #80]
	cbz	r4, .L147
	ldr	r4, [r4, #116]
	cbz	r4, .L147
	mov	r2, r6
	movs	r1, #4
	mov	r0, r5
	blx	r4
	mov	r4, r0
	cbnz	r0, .L147
	ldr	r0, [r5, #116]
	cbz	r0, .L148
	cmp	r0, r6
	beq	.L148
	bl	kfree
.L148:
	movw	r3, #990
	str	r6, [sp, #4]
	str	r3, [sp]
	movs	r1, #4
	ldr	r3, .L157
	movs	r0, #0
	ldr	r2, .L157+4
	bl	vlog
	str	r6, [r5, #116]
.L147:
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L143
.L158:
	.align	2
.L157:
	.word	.LANCHOR0+82
	.word	.LC5
	.fnend
	.size	mpi_node_set_params, .-mpi_node_set_params
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	_mpi_job_discard, %function
_mpi_job_discard:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, lr}
	.save {r4, lr}
	movs	r1, #1
	mov	r4, r0
	bl	mpi_job_cancel
	mov	r0, r4
	pop	{r4, lr}
	b	mpi_obj_unref
	.fnend
	.size	_mpi_job_discard, .-_mpi_job_discard
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	__init_completion, %function
__init_completion:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	movs	r3, #0
	ldr	r2, .L161
	str	r3, [r0], #4
	ldr	r1, .L161+4
	b	__init_swait_queue_head
.L162:
	.align	2
.L161:
	.word	.LANCHOR1
	.word	.LC6
	.fnend
	.size	__init_completion, .-__init_completion
	.align	1
	.global	mpi_dev_request_job
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_request_job, %function
mpi_dev_request_job:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r4, r5, lr}
	.save {r4, r5, lr}
	.pad #12
	mov	r4, r0
	ldr	r3, [r0, #80]
	movs	r1, #5
	ldr	r2, .L177
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1159
	str	r3, [sp]
	ldr	r3, .L177+4
	bl	vlog
	cbz	r4, .L164
	ldr	r3, [r4, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L165
.L164:
	movs	r5, #0
.L163:
	mov	r0, r5
	add	sp, sp, #12
	@ sp needed
	pop	{r4, r5, pc}
.L165:
	ldr	r3, [r4, #120]
	cbz	r3, .L167
.L170:
	ldr	r0, [r4, #120]
	bl	mpi_job_pool_request_job
	mov	r5, r0
	cbnz	r0, .L168
.L169:
	b	.L163
.L167:
	movs	r1, #10
	mov	r0, r4
	bl	mpi_job_pool_create
	mov	r5, r0
	str	r0, [r4, #120]
	cmp	r0, #0
	bne	.L170
	b	.L163
.L168:
	mov	r0, r4
	bl	mpi_obj_ref
	str	r4, [r5, #80]
	b	.L169
.L178:
	.align	2
.L177:
	.word	.LC7
	.word	.LANCHOR0+102
	.fnend
	.size	mpi_dev_request_job, .-mpi_dev_request_job
	.align	1
	.global	mpi_dev_run_job
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_run_job, %function
mpi_dev_run_job:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, r6, r7, r8, r9, lr}
	.save {r3, r4, r5, r6, r7, r8, r9, lr}
	mov	r8, r0
	mov	r6, r1
	cbz	r0, .L180
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L181
.L180:
	movs	r4, #0
.L179:
	mov	r0, r4
	pop	{r3, r4, r5, r6, r7, r8, r9, pc}
.L181:
	mov	r9, r0
	movs	r5, #0
	ldr	r4, [r9, #124]!
	subs	r4, r4, #84
.L183:
	add	r3, r4, #84
	cmp	r3, r9
	bne	.L185
	ldr	r0, [r8, #120]
	cbz	r0, .L186
	mov	r2, r6
	movs	r1, #0
	bl	mpi_job_pool_choose_job
	mov	r4, r0
	cbz	r0, .L186
	cbz	r5, .L187
	cbz	r6, .L187
	mov	r1, r5
	blx	r6
	bics	r4, r4, r0, asr #32
	it	cs
	movcs	r4, r5
.L187:
	ldr	r3, [r4, #84]
	cbz	r3, .L226
	ldr	r2, [r3, #40]
	and	r2, r2, #6
	cmp	r2, #2
	beq	.L190
.L226:
	mov	r0, r4
	bl	mpi_job_set_running
	cmp	r0, #0
	bge	.L188
	b	.L193
.L185:
	ldr	r0, [r4, #336]
	cbz	r0, .L184
	bl	mpi_queue_front_obj
	mov	r7, r0
	cbz	r0, .L184
	ldr	r3, [r0, #104]
	cmp	r3, #2
	bne	.L184
	cbz	r5, .L194
	cbz	r6, .L184
	mov	r1, r0
	mov	r0, r5
	blx	r6
	bics	r5, r5, r0, asr #32
	it	cs
	movcs	r5, r7
.L184:
	ldr	r4, [r4, #84]
	subs	r4, r4, #84
	b	.L183
.L194:
	mov	r5, r0
	b	.L184
.L186:
	cbnz	r5, .L195
.L193:
	movs	r4, #0
.L188:
	b	.L179
.L195:
	mov	r4, r5
	b	.L187
.L190:
	ldr	r0, [r3, #336]
	cbz	r0, .L192
	mov	r1, r4
	bl	mpi_queue_try_pop_obj
	cbnz	r0, .L192
	b	.L193
.L192:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L226
	.fnend
	.size	mpi_dev_run_job, .-mpi_dev_run_job
	.align	1
	.global	mpi_dev_register
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_register, %function
mpi_dev_register:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r4, r5, lr}
	.save {r4, r5, lr}
	.pad #12
	add	r3, r0, #124
	mov	r4, r0
	str	r3, [r0, #124]
	str	r3, [r0, #128]
	mov	r5, r1
	mov	r0, r2
	mov	r1, #3264
	bl	kstrdup
	movs	r3, #0
	mov	r1, r3
	orr	r2, r5, #64
	str	r0, [r4, #80]
	mov	r0, r4
	bl	mpi_obj_register
	ldr	r3, [r4, #80]
	ldr	r2, .L232
	movs	r1, #5
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1329
	str	r3, [sp]
	ldr	r3, .L232+4
	bl	vlog
	cbz	r4, .L228
	mov	r0, r4
	bl	mpi_obj_ref
.L228:
	movs	r0, #0
	add	sp, sp, #12
	@ sp needed
	pop	{r4, r5, pc}
.L233:
	.align	2
.L232:
	.word	.LC8
	.word	.LANCHOR0+122
	.fnend
	.size	mpi_dev_register, .-mpi_dev_register
	.global	__aeabi_idivmod
	.align	1
	.global	mpi_node_set_frame_rate
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_set_frame_rate, %function
mpi_node_set_frame_rate:
	.fnstart
	@ args = 0, pretend = 0, frame = 40
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, r8, r9, r10, lr}
	.save {r4, r5, r6, r7, r8, r9, r10, lr}
	mov	r7, r2
	ldr	r2, .L285
	.pad #40
	sub	sp, sp, #40
	mov	r5, r0
	ldr	r4, [r2]
	mov	r8, r2
	str	r4, [sp, #36]
	subs	r4, r1, #0
	blt	.L266
	subs	r2, r0, #1
	cmp	r2, #29
	bhi	.L266
	cbnz	r4, .L236
	mov	r3, r4
	mov	r2, r4
.L237:
	strb	r2, [r7, r3]
	adds	r3, r3, #1
	cmp	r5, r3
	bgt	.L237
.L235:
	ldr	r2, [sp, #36]
	mov	r0, r4
	ldr	r3, [r8]
	cmp	r2, r3
	beq	.L264
	bl	__stack_chk_fail
.L236:
	cmp	r0, r4
	bne	.L238
	movs	r4, #0
	str	r4, [r3]
	b	.L235
.L238:
	str	r0, [r3]
	ble	.L239
	bl	__aeabi_idivmod
	mov	r9, r0
	mov	r6, r1
	cbnz	r1, .L240
.L241:
	mov	r0, r6
	mov	r1, r9
	bl	__aeabi_idivmod
	clz	r1, r1
	lsrs	r1, r1, #5
	strb	r1, [r7, r6]
	adds	r6, r6, #1
	cmp	r5, r6
	bgt	.L241
.L242:
	movs	r4, #0
	b	.L235
.L240:
	subs	r6, r5, r4
	mov	r0, r5
	mov	r1, r6
	bl	__aeabi_idivmod
	mov	r10, r0
	mov	r9, r1
	cbnz	r1, .L267
.L244:
	mov	r0, r9
	mov	r1, r10
	bl	__aeabi_idivmod
	adds	r1, r1, #0
	it	ne
	movne	r1, #1
	strb	r1, [r7, r9]
	add	r9, r9, #1
	cmp	r5, r9
	bgt	.L244
	b	.L242
.L267:
	movs	r3, #0
	add	r1, sp, #6
	mov	r2, r3
.L243:
	strb	r2, [r3, r1]
	adds	r3, r3, #1
	cmp	r4, r3
	bne	.L243
.L245:
	mov	r2, r1
	movs	r3, #0
.L247:
	adds	r3, r3, #1
	ldrb	r0, [r2]	@ zero_extendqisi2
	cmp	r3, r6
	add	r0, r0, #1
	strb	r0, [r2], #1
	beq	.L268
	cmp	r4, r3
	bne	.L247
	mov	r3, r4
.L246:
	subs	r6, r6, r3
	bne	.L245
	mov	r3, r6
	mov	ip, #1
	mov	lr, r6
.L248:
	cmp	r4, r3
	ble	.L242
	ldrb	r2, [r1, r3]	@ zero_extendqisi2
	adds	r5, r7, r6
	movs	r0, #0
	strb	ip, [r7, r6]
.L249:
	cmp	r0, r2
	blt	.L250
	adds	r2, r2, #1
	adds	r3, r3, #1
	add	r6, r6, r2
	b	.L248
.L268:
	mov	r3, r6
	b	.L246
.L250:
	strb	lr, [r5, #1]!
	adds	r0, r0, #1
	b	.L249
.L239:
	mov	r1, r0
	mov	r0, r4
	bl	__aeabi_idivmod
	cbnz	r1, .L252
.L253:
	strb	r0, [r7, r1]
	adds	r1, r1, #1
	cmp	r5, r1
	bgt	.L253
	b	.L242
.L252:
	subs	r6, r4, r5
	mov	r0, r4
	mov	r1, r6
	bl	__aeabi_idivmod
	mov	r9, r0
	mov	r4, r1
	cbnz	r1, .L254
.L256:
	mov	r0, r4
	mov	r1, r9
	bl	__aeabi_idivmod
	cmp	r1, #0
	ite	ne
	movne	r3, #1
	moveq	r3, #2
	strb	r3, [r7, r4]
	adds	r4, r4, #1
	cmp	r5, r4
	bgt	.L256
	b	.L242
.L254:
	add	r2, sp, #6
	movs	r3, #0
	mov	r0, r3
	mov	r1, r2
.L257:
	adds	r3, r3, #1
	strb	r0, [r1], #1
	cmp	r5, r3
	bgt	.L257
.L258:
	mov	r1, r2
	movs	r3, #0
.L260:
	adds	r3, r3, #1
	ldrb	r0, [r1]	@ zero_extendqisi2
	cmp	r3, r6
	add	r0, r0, #1
	strb	r0, [r1], #1
	beq	.L259
	cmp	r5, r3
	bgt	.L260
.L259:
	subs	r6, r6, r3
	bne	.L258
	subs	r3, r7, #1
	movs	r4, #1
	subs	r7, r4, r7
.L263:
	ldrb	r6, [r2], #1	@ zero_extendqisi2
	movs	r1, #0
	strb	r4, [r3, #1]!
.L261:
	cmp	r1, r6
	blt	.L262
	adds	r1, r7, r3
	cmp	r5, r1
	bgt	.L263
	b	.L242
.L262:
	ldrb	r0, [r3]	@ zero_extendqisi2
	adds	r1, r1, #1
	adds	r0, r0, #1
	strb	r0, [r3]
	b	.L261
.L266:
	mov	r4, #-1
	b	.L235
.L264:
	add	sp, sp, #40
	@ sp needed
	pop	{r4, r5, r6, r7, r8, r9, r10, pc}
.L286:
	.align	2
.L285:
	.word	__stack_chk_guard
	.fnend
	.size	mpi_node_set_frame_rate, .-mpi_node_set_frame_rate
	.align	1
	.global	mpi_node_add_in_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_in_watcher, %function
mpi_node_add_in_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L298
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L289
.L298:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L289:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L299
	str	r3, [sp, #8]
	ldr	r3, [r0, #80]
	movs	r0, #0
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #203
	str	r3, [sp]
	ldr	r3, .L299+4
	bl	vlog
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #352]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #352]
	ble	.L291
	cbz	r3, .L291
	ldr	r2, .L299+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #416]
	str	r3, [r4, #424]
	str	r0, [r4, #376]
.L291:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L298
.L300:
	.align	2
.L299:
	.word	.LC9
	.word	.LANCHOR0+139
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_in_watcher, .-mpi_node_add_in_watcher
	.align	1
	.global	mpi_node_add_in_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_in_filter, %function
mpi_node_add_in_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L312
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L303
.L312:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L303:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L313
	str	r3, [sp, #8]
	ldr	r3, [r0, #80]
	movs	r0, #0
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #204
	str	r3, [sp]
	ldr	r3, .L313+4
	bl	vlog
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #356]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #356]
	ble	.L305
	ldr	r3, [r4, #352]
	cbz	r3, .L305
	ldr	r2, .L313+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #416]
	str	r3, [r4, #424]
	str	r0, [r4, #376]
.L305:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L312
.L314:
	.align	2
.L313:
	.word	.LC10
	.word	.LANCHOR0+163
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_in_filter, .-mpi_node_add_in_filter
	.align	1
	.global	mpi_node_add_out_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_out_watcher, %function
mpi_node_add_out_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L326
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L317
.L326:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L317:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L327
	str	r3, [sp, #8]
	ldr	r3, [r0, #80]
	movs	r0, #0
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #205
	str	r3, [sp]
	ldr	r3, .L327+4
	bl	vlog
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #364]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #364]
	ble	.L319
	cbz	r3, .L319
	ldr	r2, .L327+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #420]
	str	r3, [r4, #428]
	str	r0, [r4, #380]
.L319:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L326
.L328:
	.align	2
.L327:
	.word	.LC11
	.word	.LANCHOR0+186
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_out_watcher, .-mpi_node_add_out_watcher
	.align	1
	.global	mpi_node_add_out_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_add_out_filter, %function
mpi_node_add_out_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	cbz	r0, .L340
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L331
.L340:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L331:
	str	r1, [sp, #12]
	movs	r1, #5
	ldr	r3, [r0]
	ldr	r2, .L341
	str	r3, [sp, #8]
	ldr	r3, [r0, #80]
	movs	r0, #0
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #206
	str	r3, [sp]
	ldr	r3, .L341+4
	bl	vlog
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r6, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #368]
	cmp	r5, #0
	add	r3, r3, #1
	str	r3, [r4, #368]
	ble	.L333
	ldr	r3, [r4, #364]
	cbz	r3, .L333
	ldr	r2, .L341+8
	movs	r1, #4
	mov	r0, r5
	bl	mpi_queue_create
	movs	r3, #0
	str	r5, [r4, #420]
	str	r3, [r4, #428]
	str	r0, [r4, #380]
.L333:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r6	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L340
.L342:
	.align	2
.L341:
	.word	.LC12
	.word	.LANCHOR0+211
	.word	mpi_obj_unref
	.fnend
	.size	mpi_node_add_out_filter, .-mpi_node_add_out_filter
	.align	1
	.global	mpi_node_enable_auto_streamon
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_enable_auto_streamon, %function
mpi_node_enable_auto_streamon:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	ldr	r3, [r0, #40]
	cbz	r1, .L344
	orr	r1, r3, #16384
	lsls	r3, r3, #18
	str	r1, [r0, #40]
	bpl	.L343
	b	mpi_node_streamon
.L344:
	bic	r3, r3, #16384
	str	r3, [r0, #40]
.L343:
	bx	lr
	.fnend
	.size	mpi_node_enable_auto_streamon, .-mpi_node_enable_auto_streamon
	.align	1
	.global	mpi_node_del_in_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_in_watcher, %function
mpi_node_del_in_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L350
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L351
.L350:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L351:
	bl	mpi_obj_ref
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L361
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #207
	str	r3, [sp]
	ldr	r3, .L361+4
	bl	vlog
	ldr	r3, [r4, #352]
	cbz	r3, .L353
	subs	r3, r3, #1
	str	r3, [r4, #352]
.L353:
	mov	r0, r4
	movs	r1, #0
	bl	mpi_node_cleanup_in_buffer
	mov	r0, r4
	add	sp, sp, #16
	@ sp needed
	pop	{r4, lr}
	b	mpi_obj_unref
.L362:
	.align	2
.L361:
	.word	.LC13
	.word	.LANCHOR0+235
	.fnend
	.size	mpi_node_del_in_watcher, .-mpi_node_del_in_watcher
	.align	1
	.global	mpi_node_del_in_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_in_filter, %function
mpi_node_del_in_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L364
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L365
.L364:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L365:
	bl	mpi_obj_ref
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L375
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #208
	str	r3, [sp]
	ldr	r3, .L375+4
	bl	vlog
	ldr	r3, [r4, #356]
	cbz	r3, .L367
	subs	r3, r3, #1
	str	r3, [r4, #356]
.L367:
	mov	r0, r4
	movs	r1, #0
	bl	mpi_node_cleanup_in_buffer
	mov	r0, r4
	add	sp, sp, #16
	@ sp needed
	pop	{r4, lr}
	b	mpi_obj_unref
.L376:
	.align	2
.L375:
	.word	.LC14
	.word	.LANCHOR0+259
	.fnend
	.size	mpi_node_del_in_filter, .-mpi_node_del_in_filter
	.align	1
	.global	mpi_node_del_out_watcher
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_out_watcher, %function
mpi_node_del_out_watcher:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L378
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L379
.L378:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L379:
	bl	mpi_obj_ref
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L389
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #209
	str	r3, [sp]
	ldr	r3, .L389+4
	bl	vlog
	ldr	r3, [r4, #364]
	cbz	r3, .L381
	subs	r3, r3, #1
	str	r3, [r4, #364]
.L381:
	mov	r0, r4
	movs	r1, #0
	bl	mpi_node_cleanup_out_buffer
	mov	r0, r4
	add	sp, sp, #16
	@ sp needed
	pop	{r4, lr}
	b	mpi_obj_unref
.L390:
	.align	2
.L389:
	.word	.LC15
	.word	.LANCHOR0+282
	.fnend
	.size	mpi_node_del_out_watcher, .-mpi_node_del_out_watcher
	.align	1
	.global	mpi_node_del_out_filter
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_del_out_filter, %function
mpi_node_del_out_filter:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, lr}
	.save {r4, lr}
	.pad #16
	mov	r4, r0
	cbz	r0, .L392
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L393
.L392:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, pc}
.L393:
	bl	mpi_obj_ref
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L403
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movs	r3, #210
	str	r3, [sp]
	ldr	r3, .L403+4
	bl	vlog
	ldr	r3, [r4, #368]
	cbz	r3, .L395
	subs	r3, r3, #1
	str	r3, [r4, #368]
.L395:
	mov	r0, r4
	movs	r1, #0
	bl	mpi_node_cleanup_out_buffer
	mov	r0, r4
	add	sp, sp, #16
	@ sp needed
	pop	{r4, lr}
	b	mpi_obj_unref
.L404:
	.align	2
.L403:
	.word	.LC16
	.word	.LANCHOR0+307
	.fnend
	.size	mpi_node_del_out_filter, .-mpi_node_del_out_filter
	.align	1
	.global	mpi_dev_request_job_for_node
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_request_job_for_node, %function
mpi_dev_request_job_for_node:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	.pad #20
	sub	sp, sp, #20
	ldr	r3, [r1]
	mov	r5, r0
	mov	r4, r1
	ldr	r2, .L416
	movs	r1, #5
	str	r3, [sp, #8]
	ldr	r3, [r0, #80]
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1191
	str	r3, [sp]
	ldr	r3, .L416+4
	bl	vlog
	cbz	r4, .L406
	ldr	r3, [r4, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L407
.L406:
	movs	r5, #0
.L405:
	mov	r0, r5
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, pc}
.L407:
	mov	r0, r5
	bl	mpi_dev_request_job
	mov	r5, r0
	cbz	r0, .L409
	mov	r0, r4
	bl	mpi_obj_ref
	str	r4, [r5, #84]
.L409:
	b	.L405
.L417:
	.align	2
.L416:
	.word	.LC17
	.word	.LANCHOR0+331
	.fnend
	.size	mpi_dev_request_job_for_node, .-mpi_dev_request_job_for_node
	.align	1
	.global	mpi_dev_create_node_with_params
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_create_node_with_params, %function
mpi_dev_create_node_with_params:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, r8, r9, lr}
	.save {r4, r5, r6, r7, r8, r9, lr}
	mov	r5, r0
	.pad #20
	sub	sp, sp, #20
	mov	r6, r1
	mov	r9, r2
	mov	r8, r3
	cbz	r0, .L419
	ldr	r7, [r0, #40]
	and	r7, r7, #6
	cmp	r7, #2
	beq	.L420
.L419:
	movs	r4, #0
.L418:
	mov	r0, r4
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, r6, r7, r8, r9, pc}
.L420:
	bl	mpi_obj_ref
	ldr	r3, .L441
	mov	r1, #3520
	ldr	r0, [r3, #36]
	bl	kmem_cache_alloc
	mov	r4, r0
	cbz	r0, .L422
	mov	r3, #-1
	str	r6, [r0, #92]
	str	r3, [r0, #112]
	movs	r6, #0
	str	r5, [r0, #80]
	strd	r6, r6, [r0, #164]
	strd	r6, r6, [r0, #172]
	strd	r6, r6, [r0, #232]
	strd	r6, r6, [r0, #240]
	bl	rkos_getjiffies
	ldr	r3, .L441+4
	strd	r3, r3, [r4, #408]
	add	r3, r4, #320
	str	r3, [r4, #320]
	str	r3, [r4, #324]
	add	r3, r4, #328
	str	r3, [r4, #328]
	str	r3, [r4, #332]
	str	r0, [r4, #248]
	strd	r0, r6, [r4, #184]
	cmp	r9, #0
	beq	.L423
	ldr	r2, .L441+8
	mov	r1, r7
	mov	r0, r9
	bl	mpi_queue_create
	mov	r6, r0
	str	r0, [r4, #336]
	cbnz	r0, .L423
	mov	r0, r4
	mov	r4, r6
	bl	kfree
.L422:
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L418
.L423:
	add	r0, r4, #340
	bl	__init_completion
	add	r0, r4, #384
	bl	__init_completion
	add	r0, r4, #396
	bl	__init_completion
	movs	r3, #0
	movs	r2, #96
	movs	r1, #1
	mov	r0, r4
	bl	mpi_obj_register
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r1, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r5, #128]
	add	r3, r4, #84
	add	r0, r5, #124
	str	r3, [r5, #128]
	strd	r0, r2, [r4, #84]
	str	r3, [r2]
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r1	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r5, #104]
	cbz	r3, .L424
	mov	r0, r4
	blx	r3
	str	r0, [r4, #316]
.L424:
	cmp	r8, #0
	beq	.L425
	mov	r1, r8
	mov	r0, r4
	bl	mpi_node_set_params
.L425:
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L441+12
	movs	r0, #0
	str	r3, [sp, #8]
	ldr	r3, [r5, #80]
	str	r3, [sp, #4]
	movw	r3, #1141
	str	r3, [sp]
	ldr	r3, .L441+16
	bl	vlog
	b	.L422
.L442:
	.align	2
.L441:
	.word	kmalloc_caches
	.word	500000
	.word	_mpi_job_discard
	.word	.LC18
	.word	.LANCHOR0+360
	.fnend
	.size	mpi_dev_create_node_with_params, .-mpi_dev_create_node_with_params
	.align	1
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	atomic_add.constprop.24, %function
atomic_add.constprop.24:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	pld	[r0]
	.syntax unified
@ 223 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/atomic.h" 1
	@ atomic_add
1:	ldrex	r3, [r0]
	add	r3, r3, #1
	strex	r2, r3, [r0]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	bx	lr
	.fnend
	.size	atomic_add.constprop.24, .-atomic_add.constprop.24
	.align	1
	.global	mpi_node_destroy
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_destroy, %function
mpi_node_destroy:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	.pad #20
	sub	sp, sp, #20
	ldr	r3, [r0]
	mov	r4, r0
	ldr	r2, .L490
	movs	r1, #5
	str	r3, [sp, #8]
	ldr	r3, [r0, #80]
	movs	r0, #0
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movw	r3, #1014
	str	r3, [sp]
	ldr	r3, .L490+4
	bl	vlog
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r1, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldrd	r2, r3, [r4, #84]
	str	r3, [r2, #4]
	str	r2, [r3]
	mov	r2, #256
	mov	r3, #290
	strd	r2, r3, [r4, #84]
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r1	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #40]
	movs	r1, #1
	mov	r0, r4
	orr	r3, r3, #1024
	str	r3, [r4, #40]
	bl	mpi_node_flush
	cbz	r4, .L445
	mov	r0, r4
	bl	mpi_obj_ref
.L445:
	ldr	r3, [r4, #40]
	bic	r3, r3, #2
	str	r3, [r4, #40]
	bl	synchronize_rcu
	ldr	r0, [r4, #96]
	cbz	r0, .L446
	mov	r1, r4
	bl	mpi_buf_pool_del_user
.L446:
	add	r6, r4, #320
.L447:
	mov	r0, r6
	bl	mpi_list_pop_obj_rcu
	mov	r5, r0
	cmp	r0, #0
	bne	.L448
	add	r6, r4, #328
.L449:
	mov	r0, r6
	bl	mpi_list_pop_obj_rcu
	mov	r5, r0
	cmp	r0, #0
	bne	.L450
	ldr	r0, [r4, #336]
	cbz	r0, .L451
	mov	r1, r5
	bl	mpi_queue_destroy
.L451:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r3, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r0, [r4, #316]
	cbz	r0, .L452
	movs	r2, #0
	str	r2, [r4, #316]
.L452:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r3	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	cbz	r0, .L453
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #112]
	cbz	r3, .L453
	blx	r3
.L453:
	ldr	r3, [r4, #160]
	cbz	r3, .L454
	mov	r0, r4
	blx	r3
.L454:
	ldr	r1, [r4, #112]
	cmp	r1, #15
	bhi	.L455
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r5, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, .L490+8
	mov	r0, #-1
	ldr	r3, [r2]
	subs	r3, r3, #72
.L456:
	add	r1, r3, #72
	cmp	r1, r2
	bne	.L458
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r5	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L459:
	ldr	r5, [r4, #60]
	adds	r6, r5, #4
	add	r7, r5, #8
	mov	r0, r5
	bl	atomic_add.constprop.24
	mov	r0, r6
	bl	atomic_add.constprop.24
	ldr	r3, [r4, #44]
	cbnz	r3, .L460
	mov	r0, r7
	bl	complete_all
.L460:
	mov	r0, r4
	pld	[r6]
	bl	mpi_obj_unref
	mov	r0, r7
	bl	wait_for_completion
	.syntax unified
@ 224 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/atomic.h" 1
	@ atomic_sub
1:	ldrex	r3, [r6]
	sub	r3, r3, #1
	strex	r2, r3, [r6]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	pld	[r5]
	.syntax unified
@ 224 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/atomic.h" 1
	@ atomic_sub_return
1:	ldrex	r3, [r5]
	sub	r3, r3, #1
	strex	r2, r3, [r5]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	cbnz	r3, .L461
	mov	r0, r5
	bl	kfree
.L461:
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_cleanup_in_buffer
	mov	r0, r4
	movs	r1, #1
	bl	mpi_node_cleanup_out_buffer
	ldr	r0, [r4, #116]
	cbz	r0, .L462
	bl	kfree
.L462:
	mov	r0, r4
	add	sp, sp, #20
	@ sp needed
	pop	{r4, r5, r6, r7, lr}
	b	mpi_obj_unregister
.L448:
	mov	r1, r4
	bl	mpi_node_unbind
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L447
.L450:
	mov	r0, r4
	mov	r1, r5
	bl	mpi_node_unbind
	mov	r0, r5
	bl	mpi_obj_unref
	b	.L449
.L458:
	ldr	r1, [r4, #112]
	add	r1, r3, r1, lsl #2
	ldr	r6, [r1, #488]
	cbnz	r6, .L457
	str	r0, [r1, #488]
	ldr	r1, [r4, #112]
	adds	r1, r1, #138
	str	r0, [r3, r1, lsl #2]
.L457:
	ldr	r3, [r3, #72]
	subs	r3, r3, #72
	b	.L456
.L455:
	adds	r3, r1, #1
	beq	.L459
	ldr	r0, .L490+12
	bl	rkos_printk
	b	.L459
.L491:
	.align	2
.L490:
	.word	.LC19
	.word	.LANCHOR0+392
	.word	mpi_buf_list
	.word	.LC20
	.fnend
	.size	mpi_node_destroy, .-mpi_node_destroy
	.align	1
	.global	mpi_dev_unregister
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_dev_unregister, %function
mpi_dev_unregister:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	.pad #12
	mov	r5, r0
	ldr	r3, [r0, #80]
	movs	r1, #5
	ldr	r2, .L505
	movs	r0, #0
	str	r3, [sp, #4]
	movw	r3, #1284
	str	r3, [sp]
	ldr	r3, .L505+4
	bl	vlog
	cbz	r5, .L493
	mov	r0, r5
	bl	mpi_obj_ref
.L493:
	ldr	r3, [r5, #40]
	mov	r6, r5
	bic	r3, r3, #2
	str	r3, [r5, #40]
	bl	synchronize_rcu
	ldr	r0, [r6, #124]!
	ldr	r4, [r0], #-84
	subs	r4, r4, #84
.L494:
	add	r3, r0, #84
	cmp	r3, r6
	bne	.L495
	ldr	r0, [r5, #120]
	cbz	r0, .L496
	bl	mpi_job_pool_destroy
.L496:
	mov	r0, r5
	bl	mpi_obj_unref
	ldr	r4, [r5, #60]
	ldr	r3, [r5, #40]
	adds	r6, r4, #4
	add	r7, r4, #8
	orr	r3, r3, #4
	mov	r0, r4
	str	r3, [r5, #40]
	bl	atomic_add.constprop.24
	mov	r0, r6
	bl	atomic_add.constprop.24
	ldr	r3, [r5, #44]
	cbnz	r3, .L497
	mov	r0, r7
	bl	complete_all
.L497:
	mov	r0, r5
	pld	[r6]
	bl	mpi_obj_unref
	mov	r0, r7
	bl	wait_for_completion
	.syntax unified
@ 224 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/atomic.h" 1
	@ atomic_sub
1:	ldrex	r3, [r6]
	sub	r3, r3, #1
	strex	r2, r3, [r6]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	pld	[r4]
	.syntax unified
@ 224 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/atomic.h" 1
	@ atomic_sub_return
1:	ldrex	r3, [r4]
	sub	r3, r3, #1
	strex	r2, r3, [r4]
	teq	r2, #0
	bne	1b
@ 0 "" 2
	.thumb
	.syntax unified
	cbnz	r3, .L498
	mov	r0, r4
	bl	kfree
.L498:
	ldr	r0, [r5, #80]
	bl	kfree
	mov	r0, r5
	bl	mpi_obj_unregister
	movs	r0, #0
	add	sp, sp, #12
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L495:
	bl	mpi_node_destroy
	ldr	r3, [r4, #84]
	mov	r0, r4
	sub	r4, r3, #84
	b	.L494
.L506:
	.align	2
.L505:
	.word	.LC21
	.word	.LANCHOR0+409
	.fnend
	.size	mpi_dev_unregister, .-mpi_dev_unregister
	.align	1
	.global	add_user_to_buf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	add_user_to_buf, %function
add_user_to_buf:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, lr}
	.save {r4, r5, lr}
	cbz	r1, .L507
	ldr	r3, [r0, #112]
	adds	r3, r3, #1
	bne	.L510
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r4, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r3, #0
.L521:
	str	r3, [r0, #112]
	ldr	r3, [r0, #112]
	cmp	r3, #15
	ble	.L513
.L512:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r4	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L510:
	ldr	r3, [r0, #112]
	cmp	r3, #15
	itt	gt
	mvngt	r3, #1
	strgt	r3, [r0, #112]
	ldr	r3, [r0, #112]
	cmp	r3, #0
	blt	.L507
	cmp	r2, #0
	ite	ne
	movne	r2, #16
	moveq	r2, #0
	add	r3, r3, r2
	adds	r3, r3, #122
	str	r0, [r1, r3, lsl #2]
.L507:
	pop	{r4, r5, pc}
.L513:
	add	r5, r3, #122
	ldr	r5, [r1, r5, lsl #2]
	adds	r5, r5, #1
	beq	.L512
	adds	r3, r3, #1
	b	.L521
	.fnend
	.size	add_user_to_buf, .-add_user_to_buf
	.align	1
	.global	mpi_node_buffer_in
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_buffer_in, %function
mpi_node_buffer_in:
	.fnstart
	@ args = 0, pretend = 0, frame = 16
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, r8, r9, r10, fp, lr}
	.save {r4, r5, r6, r7, r8, r9, r10, fp, lr}
	mov	r4, r0
	.pad #44
	sub	sp, sp, #44
	mov	r6, r1
	mov	r8, r2
	cbz	r0, .L523
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L524
.L523:
	movs	r5, #32
.L522:
	mov	r0, r5
	add	sp, sp, #44
	@ sp needed
	pop	{r4, r5, r6, r7, r8, r9, r10, fp, pc}
.L524:
	add	r0, r0, #292
	bl	rkos_gettime
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r5, [r4, #40]
	ands	r5, r5, #4096
	beq	.L526
	ldr	r3, [r4, #80]
	ldr	r0, [r6]
	ldr	r1, [r4]
	ldr	r2, [r3, #80]
	ldr	r5, .L565
	ldr	r3, .L565+4
	strd	r2, r1, [sp, #4]
	movs	r1, #5
	cmp	r8, #0
	it	eq
	moveq	r3, r5
	ldr	r2, .L565+8
	strd	r0, r3, [sp, #12]
	movw	r3, #531
	movs	r0, #0
	str	r3, [sp]
	ldr	r3, .L565+12
	bl	vlog
	ldr	r1, [r4, #192]
	cmp	r1, #0
	beq	.L546
	ldr	r3, [r4, #196]
	cmp	r3, #0
	ble	.L529
	subs	r3, r3, #1
	str	r3, [r4, #196]
.L530:
	movs	r2, #1
	movs	r1, #0
	mov	r0, r4
	movs	r5, #0
	bl	count_frame_rate
	b	.L526
.L529:
	ldr	r0, [r4, #164]
	bl	__aeabi_idivmod
	add	r1, r1, r4
	ldrb	r7, [r1, #200]	@ zero_extendqisi2
	cmp	r7, #0
	beq	.L530
.L528:
	ldr	r9, .L565+12
	movs	r5, #0
	ldr	r10, .L565+20
.L531:
	adds	r7, r7, #-1
	bcc	.L526
	cmp	r8, #0
	bne	.L532
	ldr	r3, [r4, #356]
	cbz	r3, .L532
	ldr	r3, [r4, #360]
	cbz	r3, .L533
	mov	r1, r6
	mov	r0, r4
	blx	r3
.L533:
	movs	r2, #1
	movs	r1, #0
	mov	r0, r4
	bl	count_frame_rate
.L526:
	add	r6, sp, #24
	mov	r0, r6
	bl	rkos_gettime
	ldr	r3, [r4, #296]
	add	r0, sp, #32
	str	r3, [sp]
	ldr	r3, [r4, #292]
	ldm	r6, {r1, r2}
	bl	rkos_time_sub
	ldr	r1, .L565+16
	mov	r0, r4
	ldr	r2, [sp, #36]
	ldr	r3, [sp, #32]
	mla	r3, r1, r3, r2
	str	r3, [r4, #308]
	bl	mpi_obj_unref
	b	.L522
.L546:
	movs	r7, #1
	b	.L528
.L532:
	ldr	r3, [r4, #352]
	cbz	r3, .L534
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	fp, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	cbz	r6, .L535
	mov	r0, r6
	bl	mpi_obj_ref
.L535:
	ldr	r2, [r4, #424]
	ldr	r3, [r4, #416]
	ldr	r0, [r4, #376]
	cmp	r2, r3
	bcs	.L536
	mov	r1, r6
	bl	mpi_queue_push_obj
	cbz	r0, .L537
	ldr	r3, [r4, #424]
	adds	r3, r3, #1
	str	r3, [r4, #424]
.L538:
	add	r0, r4, #384
	bl	complete_all
.L539:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, fp	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L534:
	mov	r1, r6
	mov	r0, r4
	movs	r2, #0
	bl	add_user_to_buf
	ldr	r3, [r4, #80]
	mov	r2, r6
	movs	r1, #1
	ldr	r3, [r3, #116]
	blx	r3
	movs	r2, #1
	subs	r1, r0, #0
	mov	r0, r4
	it	lt
	orrlt	r5, r5, #4
	bl	count_frame_rate
	b	.L531
.L537:
	movw	r3, #555
	mov	r2, r10
	str	r3, [sp]
	movs	r1, #2
	mov	r3, r9
	orr	r5, r5, #1
	bl	vlog
	mov	r0, r6
	bl	mpi_obj_unref
	b	.L538
.L536:
	bl	mpi_queue_pop_obj
	cbnz	r0, .L540
	mov	r0, r6
	orr	r5, r5, #1
	bl	mpi_obj_unref
	b	.L539
.L540:
	bl	mpi_obj_unref
	mov	r1, r6
	ldr	r0, [r4, #376]
	bl	mpi_queue_push_obj
	cbz	r0, .L541
	orr	r5, r5, #2
	b	.L539
.L541:
	movw	r3, #570
	mov	r2, r10
	str	r3, [sp]
	movs	r1, #2
	mov	r3, r9
	orr	r5, r5, #3
	bl	vlog
	mov	r0, r6
	bl	mpi_obj_unref
	b	.L539
.L566:
	.align	2
.L565:
	.word	.LC23
	.word	.LC22
	.word	.LC24
	.word	.LANCHOR0+428
	.word	1000000
	.word	.LC25
	.fnend
	.size	mpi_node_buffer_in, .-mpi_node_buffer_in
	.align	1
	.global	mpi_node_get_in_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_get_in_buffer, %function
mpi_node_get_in_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #28
	sub	sp, sp, #28
	mov	r6, r1
	cbz	r0, .L568
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L569
.L568:
	movs	r5, #0
.L567:
	mov	r0, r5
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L569:
	bl	mpi_obj_ref
	cbz	r6, .L571
.L578:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r2, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r5, [r4, #40]
	add	r0, r4, #384
	ldr	r3, .L587
	ands	r5, r5, #4096
	bne	.L572
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #408]
	str	r5, [r4, #384]
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L573:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L567
.L572:
	movs	r1, #0
	str	r1, [r4, #384]
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #408]
	movs	r6, #1
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L571:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r7, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #352]
	cbnz	r3, .L574
.L577:
	movs	r5, #0
.L575:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r2, #1
	mov	r1, r5
	mov	r0, r4
	bl	add_user_to_buf
	b	.L573
.L574:
	ldr	r0, [r4, #376]
	bl	mpi_queue_pop_obj
	mov	r5, r0
	cbnz	r0, .L576
	cmp	r6, #0
	bne	.L577
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L578
.L576:
	ldr	r3, [r4, #80]
	ldr	r0, .L587+4
	ldr	r1, .L587+8
	ldr	r3, [r3, #80]
	cmp	r6, #0
	it	eq
	moveq	r1, r0
	ldr	r2, [r4]
	ldr	r0, [r5]
	strd	r3, r2, [sp, #4]
	movw	r3, #718
	strd	r1, r0, [sp, #12]
	movs	r1, #5
	str	r3, [sp]
	movs	r0, #0
	ldr	r3, .L587+12
	ldr	r2, .L587+16
	bl	vlog
	b	.L575
.L588:
	.align	2
.L587:
	.word	-858993459
	.word	.LC27
	.word	.LC26
	.word	.LANCHOR0+447
	.word	.LC28
	.fnend
	.size	mpi_node_get_in_buffer, .-mpi_node_get_in_buffer
	.align	1
	.global	mpi_node_pick_in_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_pick_in_buffer, %function
mpi_node_pick_in_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	movs	r1, #1
	mov	r4, r0
	bl	mpi_node_add_in_watcher
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_get_in_buffer
	mov	r5, r0
	mov	r0, r4
	bl	mpi_node_del_in_watcher
	mov	r0, r5
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_pick_in_buffer, .-mpi_node_pick_in_buffer
	.align	1
	.global	mpi_node_get_out_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_get_out_buffer, %function
mpi_node_get_out_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, lr}
	.save {r4, r5, r6, r7, lr}
	mov	r4, r0
	.pad #28
	sub	sp, sp, #28
	mov	r6, r1
	cbz	r0, .L591
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L592
.L591:
	movs	r5, #0
.L590:
	mov	r0, r5
	add	sp, sp, #28
	@ sp needed
	pop	{r4, r5, r6, r7, pc}
.L592:
	bl	mpi_obj_ref
	cbz	r6, .L594
.L601:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r2, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r5, [r4, #40]
	add	r0, r4, #396
	ldr	r3, .L610
	ands	r5, r5, #4096
	bne	.L595
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #412]
	str	r5, [r4, #396]
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L596:
	mov	r0, r4
	bl	mpi_obj_unref
	b	.L590
.L595:
	movs	r1, #0
	str	r1, [r4, #396]
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r2	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r2, [r4, #412]
	movs	r6, #1
	umull	r2, r3, r2, r3
	lsrs	r1, r3, #3
	bl	wait_for_completion_interruptible_timeout
.L594:
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r7, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	ldr	r3, [r4, #364]
	cbnz	r3, .L597
.L600:
	movs	r5, #0
.L598:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r2, #1
	mov	r1, r5
	mov	r0, r4
	bl	add_user_to_buf
	b	.L596
.L597:
	ldr	r0, [r4, #380]
	bl	mpi_queue_pop_obj
	mov	r5, r0
	cbnz	r0, .L599
	cmp	r6, #0
	bne	.L600
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	b	.L601
.L599:
	ldr	r3, [r4, #80]
	ldr	r0, .L610+4
	ldr	r1, .L610+8
	ldr	r3, [r3, #80]
	cmp	r6, #0
	it	eq
	moveq	r1, r0
	ldr	r2, [r4]
	ldr	r0, [r5]
	strd	r3, r2, [sp, #4]
	movw	r3, #771
	strd	r1, r0, [sp, #12]
	movs	r1, #5
	str	r3, [sp]
	movs	r0, #0
	ldr	r3, .L610+12
	ldr	r2, .L610+16
	bl	vlog
	b	.L598
.L611:
	.align	2
.L610:
	.word	-858993459
	.word	.LC23
	.word	.LC26
	.word	.LANCHOR0+470
	.word	.LC29
	.fnend
	.size	mpi_node_get_out_buffer, .-mpi_node_get_out_buffer
	.align	1
	.global	mpi_node_pick_out_buffer
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_pick_out_buffer, %function
mpi_node_pick_out_buffer:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, lr}
	.save {r3, r4, r5, lr}
	movs	r1, #1
	mov	r4, r0
	bl	mpi_node_add_out_watcher
	movs	r1, #1
	mov	r0, r4
	bl	mpi_node_get_out_buffer
	mov	r5, r0
	mov	r0, r4
	bl	mpi_node_del_out_watcher
	mov	r0, r5
	pop	{r3, r4, r5, pc}
	.fnend
	.size	mpi_node_pick_out_buffer, .-mpi_node_pick_out_buffer
	.align	1
	.global	mpi_node_request_buf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_request_buf, %function
mpi_node_request_buf:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	mov	r4, r0
	.pad #24
	sub	sp, sp, #24
	mov	r5, r1
	ldr	r6, [r0, #96]
	cbz	r0, .L614
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L615
.L614:
	movs	r5, #0
.L613:
	mov	r0, r5
	add	sp, sp, #24
	@ sp needed
	pop	{r4, r5, r6, pc}
.L615:
	ldr	r3, [r0, #80]
	ldr	r1, [r0]
	ldr	r2, [r3, #80]
	cbz	r5, .L619
	ldr	r3, [r5]
.L617:
	strd	r1, r3, [sp, #8]
	movs	r0, #0
	str	r2, [sp, #4]
	movw	r3, #797
	ldr	r2, .L626
	movs	r1, #5
	str	r3, [sp]
	ldr	r3, .L626+4
	bl	vlog
	mov	r1, r5
	mov	r0, r6
	bl	mpi_buf_pool_request_buf
	mov	r5, r0
	cbz	r0, .L618
	ldr	r3, [r6]
	movs	r1, #5
	ldr	r2, .L626+8
	str	r3, [sp, #16]
	ldr	r3, [r0]
	movs	r0, #0
	str	r3, [sp, #12]
	ldr	r3, [r4]
	str	r3, [sp, #8]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #4]
	movw	r3, #803
	str	r3, [sp]
	ldr	r3, .L626+4
	bl	vlog
	ldr	r3, [r6, #100]
	str	r3, [r4, #108]
.L618:
	movs	r2, #0
	mov	r1, r5
	mov	r0, r4
	bl	add_user_to_buf
	b	.L613
.L619:
	mov	r3, #-1
	b	.L617
.L627:
	.align	2
.L626:
	.word	.LC30
	.word	.LANCHOR0+494
	.word	.LC31
	.fnend
	.size	mpi_node_request_buf, .-mpi_node_request_buf
	.align	1
	.global	remove_user_from_buf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	remove_user_from_buf, %function
remove_user_from_buf:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	cbz	r1, .L628
	cmp	r0, #0
	blt	.L628
	cmp	r2, #0
	mov	r2, #0
	ite	ne
	movne	r3, #16
	moveq	r3, #0
	add	r3, r3, r0
	adds	r3, r3, #122
	str	r2, [r1, r3, lsl #2]
.L628:
	bx	lr
	.fnend
	.size	remove_user_from_buf, .-remove_user_from_buf
	.align	1
	.global	mpi_node_release_buffer_flag
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_release_buffer_flag, %function
mpi_node_release_buffer_flag:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r3, r4, r5, r6, r7, lr}
	.save {r3, r4, r5, r6, r7, lr}
	mov	r4, r0
	mov	r6, r1
	mov	r5, r2
	cbz	r0, .L636
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L637
.L636:
	pop	{r3, r4, r5, r6, r7, pc}
.L637:
	bl	mpi_obj_ref
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r7, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	movs	r2, #1
	ldr	r0, [r4, #112]
	mov	r1, r6
	bl	remove_user_from_buf
	mov	r0, r6
	bl	mpi_obj_unref
	cbz	r5, .L639
	ldr	r3, [r5]
	cbnz	r3, .L640
	ldr	r1, [r4]
	ldr	r0, .L648
	bl	rkos_printk
.L639:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
	mov	r0, r4
	pop	{r3, r4, r5, r6, r7, lr}
	b	mpi_obj_unref
.L640:
	subs	r3, r3, #1
	str	r3, [r5]
	b	.L639
.L649:
	.align	2
.L648:
	.word	.LC32
	.fnend
	.size	mpi_node_release_buffer_flag, .-mpi_node_release_buffer_flag
	.align	1
	.global	mpi_node_buffer_out
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_buffer_out, %function
mpi_node_buffer_out:
	.fnstart
	@ args = 0, pretend = 0, frame = 24
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r4, r5, r6, r7, r8, r9, r10, fp, lr}
	.save {r4, r5, r6, r7, r8, r9, r10, fp, lr}
	mov	r4, r0
	.pad #52
	sub	sp, sp, #52
	mov	r6, r1
	mov	r9, r2
	cbz	r0, .L651
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L652
.L651:
	movs	r5, #32
.L650:
	mov	r0, r5
	add	sp, sp, #52
	@ sp needed
	pop	{r4, r5, r6, r7, r8, r9, r10, fp, pc}
.L652:
	add	r0, r0, #300
	bl	rkos_gettime
	mov	r0, r4
	bl	mpi_obj_ref
	ldr	r3, [r4, #80]
	ldr	r0, [r6]
	ldr	r1, [r4]
	ldr	r2, [r3, #80]
	ldr	r5, .L694
	ldr	r3, .L694+4
	strd	r2, r1, [sp, #4]
	movs	r1, #5
	cmp	r9, #0
	it	eq
	moveq	r3, r5
	ldr	r2, .L694+8
	strd	r0, r3, [sp, #12]
	movw	r3, #613
	movs	r0, #0
	str	r3, [sp]
	ldr	r3, .L694+12
	bl	vlog
	ldr	r1, [r4, #252]
	cmp	r1, #0
	beq	.L675
	ldr	r3, [r4, #256]
	cmp	r3, #0
	ble	.L656
	subs	r3, r3, #1
	str	r3, [r4, #256]
.L657:
	movs	r2, #0
	mov	r0, r4
	mov	r1, r2
	movs	r5, #0
	bl	count_frame_rate
	b	.L660
.L656:
	ldr	r0, [r4, #232]
	bl	__aeabi_idivmod
	add	r1, r1, r4
	ldrb	r8, [r1, #260]	@ zero_extendqisi2
	cmp	r8, #0
	beq	.L657
.L655:
	movs	r5, #0
	ldr	r10, .L694+12
	ldr	fp, .L694+20
	b	.L672
.L658:
	ldr	r3, [r4, #364]
	cbz	r3, .L661
	.syntax unified
@ 29 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		mrs	r7, cpsr	@ arch_local_irq_save
	cpsid	i
@ 0 "" 2
	.thumb
	.syntax unified
	cbz	r6, .L662
	mov	r0, r6
	bl	mpi_obj_ref
.L662:
	ldr	r2, [r4, #428]
	ldr	r3, [r4, #420]
	ldr	r0, [r4, #380]
	cmp	r2, r3
	bcs	.L663
	mov	r1, r6
	bl	mpi_queue_push_obj
	cmp	r0, #0
	beq	.L664
	ldr	r3, [r4, #428]
	adds	r3, r3, #1
	str	r3, [r4, #428]
.L665:
	add	r0, r4, #396
	bl	complete_all
.L666:
	.syntax unified
@ 171 "/home/cww/ipc-sdk/rv1103b-2/sysdrv/source/kernel/arch/arm/include/asm/irqflags.h" 1
		msr	cpsr_c, r7	@ local_irq_restore
@ 0 "" 2
	.thumb
	.syntax unified
.L661:
	movs	r2, #0
	mov	r1, r6
	ldr	r0, [r4, #112]
	bl	remove_user_from_buf
	movs	r2, #0
	mov	r1, r2
	mov	r0, r4
	bl	count_frame_rate
	ldr	r7, [r4, #328]
	add	r3, r4, #328
	subs	r7, r7, #4
.L669:
	adds	r2, r7, #4
	cmp	r2, r3
	bne	.L671
.L672:
	adds	r8, r8, #-1
	bcc	.L660
	cmp	r9, #0
	bne	.L658
	ldr	r3, [r4, #368]
	cmp	r3, #0
	beq	.L658
	ldr	r3, [r4, #372]
	cbz	r3, .L659
	mov	r1, r6
	mov	r0, r4
	blx	r3
.L659:
	movs	r2, #0
	mov	r0, r4
	mov	r1, r2
	bl	count_frame_rate
.L660:
	add	r6, sp, #32
	mov	r0, r6
	bl	rkos_gettime
	ldr	r3, [r4, #304]
	add	r0, sp, #40
	str	r3, [sp]
	ldr	r3, [r4, #300]
	ldm	r6, {r1, r2}
	bl	rkos_time_sub
	ldr	r1, .L694+16
	mov	r0, r4
	ldr	r2, [sp, #44]
	ldr	r3, [sp, #40]
	mla	r3, r1, r3, r2
	str	r3, [r4, #312]
	bl	mpi_obj_unref
	b	.L650
.L664:
	mov	r3, #636
	mov	r2, fp
	str	r3, [sp]
	movs	r1, #2
	mov	r3, r10
	orr	r5, r5, #1
	bl	vlog
	mov	r0, r6
	bl	mpi_obj_unref
	b	.L665
.L663:
	bl	mpi_queue_pop_obj
	cbnz	r0, .L667
	mov	r0, r6
	orr	r5, r5, #1
	bl	mpi_obj_unref
	b	.L666
.L667:
	bl	mpi_obj_unref
	mov	r1, r6
	ldr	r0, [r4, #380]
	bl	mpi_queue_push_obj
	cbz	r0, .L668
	orr	r5, r5, #2
	b	.L666
.L668:
	mov	r3, #652
	mov	r2, fp
	str	r3, [sp]
	movs	r1, #2
	mov	r3, r10
	orr	r5, r5, #3
	bl	vlog
	mov	r0, r6
	bl	mpi_obj_unref
	b	.L666
.L671:
	movs	r2, #0
	mov	r1, r6
	ldr	r0, [r7]
	str	r3, [sp, #28]
	bl	mpi_node_buffer_in
	ldr	r3, [sp, #28]
	cbz	r0, .L670
	orr	r5, r5, #16
.L670:
	ldr	r7, [r7, #4]
	subs	r7, r7, #4
	b	.L669
.L675:
	mov	r8, #1
	b	.L655
.L695:
	.align	2
.L694:
	.word	.LC23
	.word	.LC22
	.word	.LC33
	.word	.LANCHOR0+515
	.word	1000000
	.word	.LC34
	.fnend
	.size	mpi_node_buffer_out, .-mpi_node_buffer_out
	.align	1
	.global	mpi_node_buffer_available
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	mpi_node_buffer_available, %function
mpi_node_buffer_available:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	push	{r0, r1, r2, r3, r4, r5, r6, lr}
	.save {r4, r5, r6, lr}
	.pad #16
	mov	r4, r0
	mov	r5, r1
	ldr	r6, [r0, #80]
	cbz	r0, .L697
	ldr	r3, [r0, #40]
	and	r3, r3, #6
	cmp	r3, #2
	beq	.L698
.L697:
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, pc}
.L698:
	bl	mpi_obj_ref
	ldr	r3, [r4, #40]
	lsls	r3, r3, #19
	bpl	.L701
	cbz	r5, .L702
	ldr	r3, [r4]
	movs	r1, #5
	ldr	r2, .L714
	movs	r0, #0
	str	r3, [sp, #12]
	ldr	r3, [r4, #80]
	ldr	r3, [r3, #80]
	str	r3, [sp, #8]
	ldr	r3, [r5]
	str	r3, [sp, #4]
	mov	r3, #502
	str	r3, [sp]
	ldr	r3, .L714+4
	bl	vlog
.L702:
	ldr	r3, [r6, #116]
	cbz	r3, .L701
	mov	r2, r5
	movs	r1, #0
	mov	r0, r4
	blx	r3
.L701:
	mov	r0, r4
	add	sp, sp, #16
	@ sp needed
	pop	{r4, r5, r6, lr}
	b	mpi_obj_unref
.L715:
	.align	2
.L714:
	.word	.LC35
	.word	.LANCHOR0+535
	.fnend
	.size	mpi_node_buffer_available, .-mpi_node_buffer_available
	.section	.rodata
	.set	.LANCHOR0,. + 0
	.type	__func__.36411, %object
	.size	__func__.36411, 18
__func__.36411:
	.ascii	"mpi_node_streamon\000"
	.type	__func__.36426, %object
	.size	__func__.36426, 19
__func__.36426:
	.ascii	"mpi_node_streamoff\000"
	.type	__func__.36684, %object
	.size	__func__.36684, 15
__func__.36684:
	.ascii	"mpi_node_flush\000"
	.type	__func__.36712, %object
	.size	__func__.36712, 16
__func__.36712:
	.ascii	"mpi_node_unbind\000"
	.type	__func__.36738, %object
	.size	__func__.36738, 14
__func__.36738:
	.ascii	"mpi_node_bind\000"
	.type	__func__.36753, %object
	.size	__func__.36753, 20
__func__.36753:
	.ascii	"mpi_node_set_params\000"
	.type	__func__.36860, %object
	.size	__func__.36860, 20
__func__.36860:
	.ascii	"mpi_dev_request_job\000"
	.type	__func__.36998, %object
	.size	__func__.36998, 17
__func__.36998:
	.ascii	"mpi_dev_register\000"
	.type	__func__.36151, %object
	.size	__func__.36151, 24
__func__.36151:
	.ascii	"mpi_node_add_in_watcher\000"
	.type	__func__.36165, %object
	.size	__func__.36165, 23
__func__.36165:
	.ascii	"mpi_node_add_in_filter\000"
	.type	__func__.36179, %object
	.size	__func__.36179, 25
__func__.36179:
	.ascii	"mpi_node_add_out_watcher\000"
	.type	__func__.36193, %object
	.size	__func__.36193, 24
__func__.36193:
	.ascii	"mpi_node_add_out_filter\000"
	.type	__func__.36206, %object
	.size	__func__.36206, 24
__func__.36206:
	.ascii	"mpi_node_del_in_watcher\000"
	.type	__func__.36215, %object
	.size	__func__.36215, 23
__func__.36215:
	.ascii	"mpi_node_del_in_filter\000"
	.type	__func__.36224, %object
	.size	__func__.36224, 25
__func__.36224:
	.ascii	"mpi_node_del_out_watcher\000"
	.type	__func__.36233, %object
	.size	__func__.36233, 24
__func__.36233:
	.ascii	"mpi_node_del_out_filter\000"
	.type	__func__.36874, %object
	.size	__func__.36874, 29
__func__.36874:
	.ascii	"mpi_dev_request_job_for_node\000"
	.type	__func__.36847, %object
	.size	__func__.36847, 32
__func__.36847:
	.ascii	"mpi_dev_create_node_with_params\000"
	.type	__func__.36768, %object
	.size	__func__.36768, 17
__func__.36768:
	.ascii	"mpi_node_destroy\000"
	.type	__func__.36959, %object
	.size	__func__.36959, 19
__func__.36959:
	.ascii	"mpi_dev_unregister\000"
	.type	__func__.36476, %object
	.size	__func__.36476, 19
__func__.36476:
	.ascii	"mpi_node_buffer_in\000"
	.type	__func__.36614, %object
	.size	__func__.36614, 23
__func__.36614:
	.ascii	"mpi_node_get_in_buffer\000"
	.type	__func__.36651, %object
	.size	__func__.36651, 24
__func__.36651:
	.ascii	"mpi_node_get_out_buffer\000"
	.type	__func__.36665, %object
	.size	__func__.36665, 21
__func__.36665:
	.ascii	"mpi_node_request_buf\000"
	.type	__func__.36516, %object
	.size	__func__.36516, 20
__func__.36516:
	.ascii	"mpi_node_buffer_out\000"
	.type	__func__.36459, %object
	.size	__func__.36459, 26
__func__.36459:
	.ascii	"mpi_node_buffer_available\000"
	.data
	.align	2
	.type	___modver_attr, %object
	.size	___modver_attr, 36
___modver_attr:
	.word	.LC36
	.short	292
	.space	2
	.word	__modver_version_show
	.space	16
	.word	.LC37
	.word	.LC38
	.bss
	.set	.LANCHOR1,. + 0
	.type	__key.13574, %object
	.size	__key.13574, 0
__key.13574:
	.section	.modinfo,"a"
	.type	__UNIQUE_ID_version255, %object
	.size	__UNIQUE_ID_version255, 19
__UNIQUE_ID_version255:
	.ascii	"rockit.version=0.1\000"
	.type	__UNIQUE_ID_license254, %object
	.size	__UNIQUE_ID_license254, 19
__UNIQUE_ID_license254:
	.ascii	"rockit.license=GPL\000"
	.type	__UNIQUE_ID_file253, %object
	.size	__UNIQUE_ID_file253, 37
__UNIQUE_ID_file253:
	.ascii	"rockit.file=drivers/rockit-ko/rockit\000"
	.type	__UNIQUE_ID_author252, %object
	.size	__UNIQUE_ID_author252, 23
__UNIQUE_ID_author252:
	.ascii	"rockit.author=Rockchip\000"
	.section	.rodata.str1.1,"aMS",%progbits,1
.LC0:
	.ascii	"node(%s-%d) stream on\000"
.LC1:
	.ascii	"node(%s-%d) stream off\000"
.LC2:
	.ascii	"node(%s-%d) flushing\000"
.LC3:
	.ascii	"unbinding source(%s-%d) sink(%s-%d)\000"
.LC4:
	.ascii	"bind source(%s-%d) sink(%s-%d)\000"
.LC5:
	.ascii	"\033[1;32m>>>>>> mpi_node_set_params params:%p\033["
	.ascii	"0m\000"
.LC6:
	.ascii	"&x->wait\000"
.LC7:
	.ascii	"device(%s) request job\000"
.LC8:
	.ascii	"device(%s) registered\000"
.LC9:
	.ascii	"node(%s-%d) add in watcherdepth(%d)\000"
.LC10:
	.ascii	"node(%s-%d) add in filterdepth(%d)\000"
.LC11:
	.ascii	"node(%s-%d) add out watcherdepth(%d)\000"
.LC12:
	.ascii	"node(%s-%d) add out filterdepth(%d)\000"
.LC13:
	.ascii	"node(%s-%d) del in watcher\000"
.LC14:
	.ascii	"node(%s-%d) del in filter\000"
.LC15:
	.ascii	"node(%s-%d) del out watcher\000"
.LC16:
	.ascii	"node(%s-%d) del out filter\000"
.LC17:
	.ascii	"device(%s) request job for node %d\000"
.LC18:
	.ascii	"node(%s-%d) created\000"
.LC19:
	.ascii	"node(%s-%d) destroying\000"
.LC20:
	.ascii	"node buf user id error = %d\000"
.LC21:
	.ascii	"device(%s) unregistering\000"
.LC22:
	.ascii	" injected\000"
.LC23:
	.ascii	"\000"
.LC24:
	.ascii	"node(%s-%d) input buf(%d)%s\000"
.LC25:
	.ascii	"\033[1;31mpush in buf queue fail\033[0m\000"
.LC26:
	.ascii	" next\000"
.LC27:
	.ascii	"current\000"
.LC28:
	.ascii	"node(%s-%d) got%s input buf(%d)\000"
.LC29:
	.ascii	"node(%s-%d) got%s output buf(%d)\000"
.LC30:
	.ascii	"node(%s-%d) request buf(%d)\000"
.LC31:
	.ascii	"node(%s-%d) got buf(%d) from pool(%d)\000"
.LC32:
	.ascii	"watcher release error node_id = %d\000"
.LC33:
	.ascii	"node(%s-%d) output buf(%d)%s\000"
.LC34:
	.ascii	"\033[1;31mpush out buf queue fail\033[0m\000"
.LC35:
	.ascii	"buf(%d) available for node(%s-%d)\000"
.LC36:
	.ascii	"version\000"
.LC37:
	.ascii	"rockit\000"
.LC38:
	.ascii	"0.1\000"
	.section	___ksymtab_gpl+mpi_dev_create_node_with_params,"a"
	.align	2
	.type	__ksymtab_mpi_dev_create_node_with_params, %object
	.size	__ksymtab_mpi_dev_create_node_with_params, 12
__ksymtab_mpi_dev_create_node_with_params:
	.word	mpi_dev_create_node_with_params
	.word	__kstrtab_mpi_dev_create_node_with_params
	.word	__kstrtabns_mpi_dev_create_node_with_params
	.section	___ksymtab_gpl+mpi_dev_register,"a"
	.align	2
	.type	__ksymtab_mpi_dev_register, %object
	.size	__ksymtab_mpi_dev_register, 12
__ksymtab_mpi_dev_register:
	.word	mpi_dev_register
	.word	__kstrtab_mpi_dev_register
	.word	__kstrtabns_mpi_dev_register
	.section	___ksymtab_gpl+mpi_dev_request_job,"a"
	.align	2
	.type	__ksymtab_mpi_dev_request_job, %object
	.size	__ksymtab_mpi_dev_request_job, 12
__ksymtab_mpi_dev_request_job:
	.word	mpi_dev_request_job
	.word	__kstrtab_mpi_dev_request_job
	.word	__kstrtabns_mpi_dev_request_job
	.section	___ksymtab_gpl+mpi_dev_request_job_for_node,"a"
	.align	2
	.type	__ksymtab_mpi_dev_request_job_for_node, %object
	.size	__ksymtab_mpi_dev_request_job_for_node, 12
__ksymtab_mpi_dev_request_job_for_node:
	.word	mpi_dev_request_job_for_node
	.word	__kstrtab_mpi_dev_request_job_for_node
	.word	__kstrtabns_mpi_dev_request_job_for_node
	.section	___ksymtab_gpl+mpi_dev_run_job,"a"
	.align	2
	.type	__ksymtab_mpi_dev_run_job, %object
	.size	__ksymtab_mpi_dev_run_job, 12
__ksymtab_mpi_dev_run_job:
	.word	mpi_dev_run_job
	.word	__kstrtab_mpi_dev_run_job
	.word	__kstrtabns_mpi_dev_run_job
	.section	___ksymtab_gpl+mpi_dev_unregister,"a"
	.align	2
	.type	__ksymtab_mpi_dev_unregister, %object
	.size	__ksymtab_mpi_dev_unregister, 12
__ksymtab_mpi_dev_unregister:
	.word	mpi_dev_unregister
	.word	__kstrtab_mpi_dev_unregister
	.word	__kstrtabns_mpi_dev_unregister
	.section	___ksymtab_gpl+mpi_node_add_in_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_in_filter, %object
	.size	__ksymtab_mpi_node_add_in_filter, 12
__ksymtab_mpi_node_add_in_filter:
	.word	mpi_node_add_in_filter
	.word	__kstrtab_mpi_node_add_in_filter
	.word	__kstrtabns_mpi_node_add_in_filter
	.section	___ksymtab_gpl+mpi_node_add_in_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_in_watcher, %object
	.size	__ksymtab_mpi_node_add_in_watcher, 12
__ksymtab_mpi_node_add_in_watcher:
	.word	mpi_node_add_in_watcher
	.word	__kstrtab_mpi_node_add_in_watcher
	.word	__kstrtabns_mpi_node_add_in_watcher
	.section	___ksymtab_gpl+mpi_node_add_out_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_out_filter, %object
	.size	__ksymtab_mpi_node_add_out_filter, 12
__ksymtab_mpi_node_add_out_filter:
	.word	mpi_node_add_out_filter
	.word	__kstrtab_mpi_node_add_out_filter
	.word	__kstrtabns_mpi_node_add_out_filter
	.section	___ksymtab_gpl+mpi_node_add_out_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_add_out_watcher, %object
	.size	__ksymtab_mpi_node_add_out_watcher, 12
__ksymtab_mpi_node_add_out_watcher:
	.word	mpi_node_add_out_watcher
	.word	__kstrtab_mpi_node_add_out_watcher
	.word	__kstrtabns_mpi_node_add_out_watcher
	.section	___ksymtab_gpl+mpi_node_bind,"a"
	.align	2
	.type	__ksymtab_mpi_node_bind, %object
	.size	__ksymtab_mpi_node_bind, 12
__ksymtab_mpi_node_bind:
	.word	mpi_node_bind
	.word	__kstrtab_mpi_node_bind
	.word	__kstrtabns_mpi_node_bind
	.section	___ksymtab_gpl+mpi_node_buffer_in,"a"
	.align	2
	.type	__ksymtab_mpi_node_buffer_in, %object
	.size	__ksymtab_mpi_node_buffer_in, 12
__ksymtab_mpi_node_buffer_in:
	.word	mpi_node_buffer_in
	.word	__kstrtab_mpi_node_buffer_in
	.word	__kstrtabns_mpi_node_buffer_in
	.section	___ksymtab_gpl+mpi_node_buffer_out,"a"
	.align	2
	.type	__ksymtab_mpi_node_buffer_out, %object
	.size	__ksymtab_mpi_node_buffer_out, 12
__ksymtab_mpi_node_buffer_out:
	.word	mpi_node_buffer_out
	.word	__kstrtab_mpi_node_buffer_out
	.word	__kstrtabns_mpi_node_buffer_out
	.section	___ksymtab_gpl+mpi_node_del_in_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_in_filter, %object
	.size	__ksymtab_mpi_node_del_in_filter, 12
__ksymtab_mpi_node_del_in_filter:
	.word	mpi_node_del_in_filter
	.word	__kstrtab_mpi_node_del_in_filter
	.word	__kstrtabns_mpi_node_del_in_filter
	.section	___ksymtab_gpl+mpi_node_del_in_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_in_watcher, %object
	.size	__ksymtab_mpi_node_del_in_watcher, 12
__ksymtab_mpi_node_del_in_watcher:
	.word	mpi_node_del_in_watcher
	.word	__kstrtab_mpi_node_del_in_watcher
	.word	__kstrtabns_mpi_node_del_in_watcher
	.section	___ksymtab_gpl+mpi_node_del_out_filter,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_out_filter, %object
	.size	__ksymtab_mpi_node_del_out_filter, 12
__ksymtab_mpi_node_del_out_filter:
	.word	mpi_node_del_out_filter
	.word	__kstrtab_mpi_node_del_out_filter
	.word	__kstrtabns_mpi_node_del_out_filter
	.section	___ksymtab_gpl+mpi_node_del_out_watcher,"a"
	.align	2
	.type	__ksymtab_mpi_node_del_out_watcher, %object
	.size	__ksymtab_mpi_node_del_out_watcher, 12
__ksymtab_mpi_node_del_out_watcher:
	.word	mpi_node_del_out_watcher
	.word	__kstrtab_mpi_node_del_out_watcher
	.word	__kstrtabns_mpi_node_del_out_watcher
	.section	___ksymtab_gpl+mpi_node_destroy,"a"
	.align	2
	.type	__ksymtab_mpi_node_destroy, %object
	.size	__ksymtab_mpi_node_destroy, 12
__ksymtab_mpi_node_destroy:
	.word	mpi_node_destroy
	.word	__kstrtab_mpi_node_destroy
	.word	__kstrtabns_mpi_node_destroy
	.section	___ksymtab_gpl+mpi_node_enable_auto_streamon,"a"
	.align	2
	.type	__ksymtab_mpi_node_enable_auto_streamon, %object
	.size	__ksymtab_mpi_node_enable_auto_streamon, 12
__ksymtab_mpi_node_enable_auto_streamon:
	.word	mpi_node_enable_auto_streamon
	.word	__kstrtab_mpi_node_enable_auto_streamon
	.word	__kstrtabns_mpi_node_enable_auto_streamon
	.section	___ksymtab_gpl+mpi_node_flush,"a"
	.align	2
	.type	__ksymtab_mpi_node_flush, %object
	.size	__ksymtab_mpi_node_flush, 12
__ksymtab_mpi_node_flush:
	.word	mpi_node_flush
	.word	__kstrtab_mpi_node_flush
	.word	__kstrtabns_mpi_node_flush
	.section	___ksymtab_gpl+mpi_node_force_lost_frame,"a"
	.align	2
	.type	__ksymtab_mpi_node_force_lost_frame, %object
	.size	__ksymtab_mpi_node_force_lost_frame, 12
__ksymtab_mpi_node_force_lost_frame:
	.word	mpi_node_force_lost_frame
	.word	__kstrtab_mpi_node_force_lost_frame
	.word	__kstrtabns_mpi_node_force_lost_frame
	.section	___ksymtab_gpl+mpi_node_get_in_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_get_in_buffer, %object
	.size	__ksymtab_mpi_node_get_in_buffer, 12
__ksymtab_mpi_node_get_in_buffer:
	.word	mpi_node_get_in_buffer
	.word	__kstrtab_mpi_node_get_in_buffer
	.word	__kstrtabns_mpi_node_get_in_buffer
	.section	___ksymtab_gpl+mpi_node_get_out_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_get_out_buffer, %object
	.size	__ksymtab_mpi_node_get_out_buffer, 12
__ksymtab_mpi_node_get_out_buffer:
	.word	mpi_node_get_out_buffer
	.word	__kstrtab_mpi_node_get_out_buffer
	.word	__kstrtabns_mpi_node_get_out_buffer
	.section	___ksymtab_gpl+mpi_node_pick_in_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_pick_in_buffer, %object
	.size	__ksymtab_mpi_node_pick_in_buffer, 12
__ksymtab_mpi_node_pick_in_buffer:
	.word	mpi_node_pick_in_buffer
	.word	__kstrtab_mpi_node_pick_in_buffer
	.word	__kstrtabns_mpi_node_pick_in_buffer
	.section	___ksymtab_gpl+mpi_node_pick_out_buffer,"a"
	.align	2
	.type	__ksymtab_mpi_node_pick_out_buffer, %object
	.size	__ksymtab_mpi_node_pick_out_buffer, 12
__ksymtab_mpi_node_pick_out_buffer:
	.word	mpi_node_pick_out_buffer
	.word	__kstrtab_mpi_node_pick_out_buffer
	.word	__kstrtabns_mpi_node_pick_out_buffer
	.section	___ksymtab_gpl+mpi_node_release_buffer_flag,"a"
	.align	2
	.type	__ksymtab_mpi_node_release_buffer_flag, %object
	.size	__ksymtab_mpi_node_release_buffer_flag, 12
__ksymtab_mpi_node_release_buffer_flag:
	.word	mpi_node_release_buffer_flag
	.word	__kstrtab_mpi_node_release_buffer_flag
	.word	__kstrtabns_mpi_node_release_buffer_flag
	.section	___ksymtab_gpl+mpi_node_request_buf,"a"
	.align	2
	.type	__ksymtab_mpi_node_request_buf, %object
	.size	__ksymtab_mpi_node_request_buf, 12
__ksymtab_mpi_node_request_buf:
	.word	mpi_node_request_buf
	.word	__kstrtab_mpi_node_request_buf
	.word	__kstrtabns_mpi_node_request_buf
	.section	___ksymtab_gpl+mpi_node_set_frame_rate,"a"
	.align	2
	.type	__ksymtab_mpi_node_set_frame_rate, %object
	.size	__ksymtab_mpi_node_set_frame_rate, 12
__ksymtab_mpi_node_set_frame_rate:
	.word	mpi_node_set_frame_rate
	.word	__kstrtab_mpi_node_set_frame_rate
	.word	__kstrtabns_mpi_node_set_frame_rate
	.section	___ksymtab_gpl+mpi_node_set_params,"a"
	.align	2
	.type	__ksymtab_mpi_node_set_params, %object
	.size	__ksymtab_mpi_node_set_params, 12
__ksymtab_mpi_node_set_params:
	.word	mpi_node_set_params
	.word	__kstrtab_mpi_node_set_params
	.word	__kstrtabns_mpi_node_set_params
	.section	___ksymtab_gpl+mpi_node_stream_pause,"a"
	.align	2
	.type	__ksymtab_mpi_node_stream_pause, %object
	.size	__ksymtab_mpi_node_stream_pause, 12
__ksymtab_mpi_node_stream_pause:
	.word	mpi_node_stream_pause
	.word	__kstrtab_mpi_node_stream_pause
	.word	__kstrtabns_mpi_node_stream_pause
	.section	___ksymtab_gpl+mpi_node_streamoff,"a"
	.align	2
	.type	__ksymtab_mpi_node_streamoff, %object
	.size	__ksymtab_mpi_node_streamoff, 12
__ksymtab_mpi_node_streamoff:
	.word	mpi_node_streamoff
	.word	__kstrtab_mpi_node_streamoff
	.word	__kstrtabns_mpi_node_streamoff
	.section	___ksymtab_gpl+mpi_node_streamon,"a"
	.align	2
	.type	__ksymtab_mpi_node_streamon, %object
	.size	__ksymtab_mpi_node_streamon, 12
__ksymtab_mpi_node_streamon:
	.word	mpi_node_streamon
	.word	__kstrtab_mpi_node_streamon
	.word	__kstrtabns_mpi_node_streamon
	.section	___ksymtab_gpl+mpi_node_unbind,"a"
	.align	2
	.type	__ksymtab_mpi_node_unbind, %object
	.size	__ksymtab_mpi_node_unbind, 12
__ksymtab_mpi_node_unbind:
	.word	mpi_node_unbind
	.word	__kstrtab_mpi_node_unbind
	.word	__kstrtabns_mpi_node_unbind
	.section	__modver,"a"
	.align	2
	.type	__modver_attr, %object
	.size	__modver_attr, 4
__modver_attr:
	.word	___modver_attr
	.ident	"GCC: (crosstool-NG 1.24.0 - v1.0.50) 8.3.0"
	.section	.note.GNU-stack,"",%progbits
