	.arch armv7-a
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 4
	.eabi_attribute 34, 1
	.eabi_attribute 18, 2
	.file	"osal_string.c"
	.text
	.syntax unified
	.syntax unified
	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strcpy:					
	.asciz 	"rkos_strcpy"					
__kstrtabns_rkos_strcpy:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strncpy:					
	.asciz 	"rkos_strncpy"					
__kstrtabns_rkos_strncpy:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strlcpy:					
	.asciz 	"rkos_strlcpy"					
__kstrtabns_rkos_strlcpy:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strcat:					
	.asciz 	"rkos_strcat"					
__kstrtabns_rkos_strcat:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strncat:					
	.asciz 	"rkos_strncat"					
__kstrtabns_rkos_strncat:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strlcat:					
	.asciz 	"rkos_strlcat"					
__kstrtabns_rkos_strlcat:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strcmp:					
	.asciz 	"rkos_strcmp"					
__kstrtabns_rkos_strcmp:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strncmp:					
	.asciz 	"rkos_strncmp"					
__kstrtabns_rkos_strncmp:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strnicmp:					
	.asciz 	"rkos_strnicmp"					
__kstrtabns_rkos_strnicmp:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strcasecmp:					
	.asciz 	"rkos_strcasecmp"					
__kstrtabns_rkos_strcasecmp:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strncasecmp:					
	.asciz 	"rkos_strncasecmp"					
__kstrtabns_rkos_strncasecmp:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strchr:					
	.asciz 	"rkos_strchr"					
__kstrtabns_rkos_strchr:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strnchr:					
	.asciz 	"rkos_strnchr"					
__kstrtabns_rkos_strnchr:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strrchr:					
	.asciz 	"rkos_strrchr"					
__kstrtabns_rkos_strrchr:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strstr:					
	.asciz 	"rkos_strstr"					
__kstrtabns_rkos_strstr:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strnstr:					
	.asciz 	"rkos_strnstr"					
__kstrtabns_rkos_strnstr:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strlen:					
	.asciz 	"rkos_strlen"					
__kstrtabns_rkos_strlen:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strnlen:					
	.asciz 	"rkos_strnlen"					
__kstrtabns_rkos_strnlen:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strpbrk:					
	.asciz 	"rkos_strpbrk"					
__kstrtabns_rkos_strpbrk:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strsep:					
	.asciz 	"rkos_strsep"					
__kstrtabns_rkos_strsep:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strspn:					
	.asciz 	"rkos_strspn"					
__kstrtabns_rkos_strspn:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strcspn:					
	.asciz 	"rkos_strcspn"					
__kstrtabns_rkos_strcspn:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_memset:					
	.asciz 	"rkos_memset"					
__kstrtabns_rkos_memset:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_memcpy:					
	.asciz 	"rkos_memcpy"					
__kstrtabns_rkos_memcpy:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_memmove:					
	.asciz 	"rkos_memmove"					
__kstrtabns_rkos_memmove:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_memscan:					
	.asciz 	"rkos_memscan"					
__kstrtabns_rkos_memscan:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_memcmp:					
	.asciz 	"rkos_memcmp"					
__kstrtabns_rkos_memcmp:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_memchr:					
	.asciz 	"rkos_memchr"					
__kstrtabns_rkos_memchr:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_memchr_inv:					
	.asciz 	"rkos_memchr_inv"					
__kstrtabns_rkos_memchr_inv:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strtoull:					
	.asciz 	"rkos_strtoull"					
__kstrtabns_rkos_strtoull:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strtoul:					
	.asciz 	"rkos_strtoul"					
__kstrtabns_rkos_strtoul:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strtol:					
	.asciz 	"rkos_strtol"					
__kstrtabns_rkos_strtol:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_strtoll:					
	.asciz 	"rkos_strtoll"					
__kstrtabns_rkos_strtoll:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_snprintf:					
	.asciz 	"rkos_snprintf"					
__kstrtabns_rkos_snprintf:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_scnprintf:					
	.asciz 	"rkos_scnprintf"					
__kstrtabns_rkos_scnprintf:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_sprintf:					
	.asciz 	"rkos_sprintf"					
__kstrtabns_rkos_sprintf:					
	.asciz 	""					
	.previous						

	.section "__ksymtab_strings","aMS",%progbits,1	
__kstrtab_rkos_sscanf:					
	.asciz 	"rkos_sscanf"					
__kstrtabns_rkos_sscanf:					
	.asciz 	""					
	.previous						

	.thumb
	.syntax unified
	.align	1
	.global	rkos_strnicmp
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strnicmp, %function
rkos_strnicmp:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	movs	r0, #0
	bx	lr
	.fnend
	.size	rkos_strnicmp, .-rkos_strnicmp
	.align	1
	.global	rkos_strcpy
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strcpy, %function
rkos_strcpy:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strcpy
	.fnend
	.size	rkos_strcpy, .-rkos_strcpy
	.align	1
	.global	rkos_strncpy
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strncpy, %function
rkos_strncpy:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strncpy
	.fnend
	.size	rkos_strncpy, .-rkos_strncpy
	.align	1
	.global	rkos_strlcpy
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strlcpy, %function
rkos_strlcpy:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strlcpy
	.fnend
	.size	rkos_strlcpy, .-rkos_strlcpy
	.align	1
	.global	rkos_strcat
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strcat, %function
rkos_strcat:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strcat
	.fnend
	.size	rkos_strcat, .-rkos_strcat
	.align	1
	.global	rkos_strncat
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strncat, %function
rkos_strncat:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strncat
	.fnend
	.size	rkos_strncat, .-rkos_strncat
	.align	1
	.global	rkos_strlcat
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strlcat, %function
rkos_strlcat:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strlcat
	.fnend
	.size	rkos_strlcat, .-rkos_strlcat
	.align	1
	.global	rkos_strcmp
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strcmp, %function
rkos_strcmp:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strcmp
	.fnend
	.size	rkos_strcmp, .-rkos_strcmp
	.align	1
	.global	rkos_strncmp
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strncmp, %function
rkos_strncmp:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strncmp
	.fnend
	.size	rkos_strncmp, .-rkos_strncmp
	.align	1
	.global	rkos_strcasecmp
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strcasecmp, %function
rkos_strcasecmp:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strcasecmp
	.fnend
	.size	rkos_strcasecmp, .-rkos_strcasecmp
	.align	1
	.global	rkos_strncasecmp
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strncasecmp, %function
rkos_strncasecmp:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strncasecmp
	.fnend
	.size	rkos_strncasecmp, .-rkos_strncasecmp
	.align	1
	.global	rkos_strchr
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strchr, %function
rkos_strchr:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strchr
	.fnend
	.size	rkos_strchr, .-rkos_strchr
	.align	1
	.global	rkos_strnchr
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strnchr, %function
rkos_strnchr:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strnchr
	.fnend
	.size	rkos_strnchr, .-rkos_strnchr
	.align	1
	.global	rkos_strrchr
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strrchr, %function
rkos_strrchr:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strrchr
	.fnend
	.size	rkos_strrchr, .-rkos_strrchr
	.align	1
	.global	rkos_strstr
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strstr, %function
rkos_strstr:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strstr
	.fnend
	.size	rkos_strstr, .-rkos_strstr
	.align	1
	.global	rkos_strnstr
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strnstr, %function
rkos_strnstr:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strnstr
	.fnend
	.size	rkos_strnstr, .-rkos_strnstr
	.align	1
	.global	rkos_strlen
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strlen, %function
rkos_strlen:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strlen
	.fnend
	.size	rkos_strlen, .-rkos_strlen
	.align	1
	.global	rkos_strnlen
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strnlen, %function
rkos_strnlen:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strnlen
	.fnend
	.size	rkos_strnlen, .-rkos_strnlen
	.align	1
	.global	rkos_strpbrk
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strpbrk, %function
rkos_strpbrk:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strpbrk
	.fnend
	.size	rkos_strpbrk, .-rkos_strpbrk
	.align	1
	.global	rkos_strsep
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strsep, %function
rkos_strsep:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strsep
	.fnend
	.size	rkos_strsep, .-rkos_strsep
	.align	1
	.global	rkos_strspn
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strspn, %function
rkos_strspn:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strspn
	.fnend
	.size	rkos_strspn, .-rkos_strspn
	.align	1
	.global	rkos_strcspn
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strcspn, %function
rkos_strcspn:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	strcspn
	.fnend
	.size	rkos_strcspn, .-rkos_strcspn
	.align	1
	.global	rkos_memset
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_memset, %function
rkos_memset:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	memset
	.fnend
	.size	rkos_memset, .-rkos_memset
	.align	1
	.global	rkos_memcpy
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_memcpy, %function
rkos_memcpy:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	memcpy
	.fnend
	.size	rkos_memcpy, .-rkos_memcpy
	.align	1
	.global	rkos_memmove
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_memmove, %function
rkos_memmove:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	memmove
	.fnend
	.size	rkos_memmove, .-rkos_memmove
	.align	1
	.global	rkos_memscan
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_memscan, %function
rkos_memscan:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	memscan
	.fnend
	.size	rkos_memscan, .-rkos_memscan
	.align	1
	.global	rkos_memcmp
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_memcmp, %function
rkos_memcmp:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	memcmp
	.fnend
	.size	rkos_memcmp, .-rkos_memcmp
	.align	1
	.global	rkos_memchr
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_memchr, %function
rkos_memchr:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	memchr
	.fnend
	.size	rkos_memchr, .-rkos_memchr
	.align	1
	.global	rkos_memchr_inv
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_memchr_inv, %function
rkos_memchr_inv:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	memchr_inv
	.fnend
	.size	rkos_memchr_inv, .-rkos_memchr_inv
	.align	1
	.global	rkos_strtoull
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strtoull, %function
rkos_strtoull:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	simple_strtoull
	.fnend
	.size	rkos_strtoull, .-rkos_strtoull
	.align	1
	.global	rkos_strtoul
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strtoul, %function
rkos_strtoul:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	simple_strtoul
	.fnend
	.size	rkos_strtoul, .-rkos_strtoul
	.align	1
	.global	rkos_strtol
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strtol, %function
rkos_strtol:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	simple_strtol
	.fnend
	.size	rkos_strtol, .-rkos_strtol
	.align	1
	.global	rkos_strtoll
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_strtoll, %function
rkos_strtoll:
	.fnstart
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, uses_anonymous_args = 0
	@ link register save eliminated.
	b	simple_strtoll
	.fnend
	.size	rkos_strtoll, .-rkos_strtoll
	.align	1
	.global	rkos_snprintf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_snprintf, %function
rkos_snprintf:
	.fnstart
	@ args = 4, pretend = 8, frame = 8
	@ frame_needed = 0, uses_anonymous_args = 1
	push	{r2, r3}
	.save {r2, r3}
	push	{r0, r1, r2, lr}
	.save {lr}
	.pad #12
	add	r3, sp, #16
	ldr	r2, [r3], #4
	str	r3, [sp, #4]
	bl	vsnprintf
	add	sp, sp, #12
	@ sp needed
	ldr	lr, [sp], #4
	add	sp, sp, #8
	bx	lr
	.fnend
	.size	rkos_snprintf, .-rkos_snprintf
	.align	1
	.global	rkos_sprintf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_sprintf, %function
rkos_sprintf:
	.fnstart
	@ args = 4, pretend = 12, frame = 8
	@ frame_needed = 0, uses_anonymous_args = 1
	push	{r1, r2, r3}
	.save {r1, r2, r3}
	push	{r0, r1, lr}
	.save {lr}
	.pad #8
	add	r3, sp, #12
	mvn	r1, #-2147483648
	ldr	r2, [r3], #4
	str	r3, [sp, #4]
	bl	vsnprintf
	add	sp, sp, #8
	@ sp needed
	ldr	lr, [sp], #4
	add	sp, sp, #12
	bx	lr
	.fnend
	.size	rkos_sprintf, .-rkos_sprintf
	.align	1
	.global	rkos_scnprintf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_scnprintf, %function
rkos_scnprintf:
	.fnstart
	@ args = 4, pretend = 8, frame = 8
	@ frame_needed = 0, uses_anonymous_args = 1
	push	{r2, r3}
	.save {r2, r3}
	push	{r0, r1, r2, lr}
	.save {lr}
	.pad #12
	add	r3, sp, #16
	ldr	r2, [r3], #4
	str	r3, [sp, #4]
	bl	vscnprintf
	add	sp, sp, #12
	@ sp needed
	ldr	lr, [sp], #4
	add	sp, sp, #8
	bx	lr
	.fnend
	.size	rkos_scnprintf, .-rkos_scnprintf
	.align	1
	.global	rkos_sscanf
	.syntax unified
	.thumb
	.thumb_func
	.fpu softvfp
	.type	rkos_sscanf, %function
rkos_sscanf:
	.fnstart
	@ args = 4, pretend = 12, frame = 8
	@ frame_needed = 0, uses_anonymous_args = 1
	push	{r1, r2, r3}
	.save {r1, r2, r3}
	push	{r0, r1, lr}
	.save {lr}
	.pad #8
	add	r2, sp, #12
	ldr	r1, [r2], #4
	str	r2, [sp, #4]
	bl	vsscanf
	add	sp, sp, #8
	@ sp needed
	ldr	lr, [sp], #4
	add	sp, sp, #12
	bx	lr
	.fnend
	.size	rkos_sscanf, .-rkos_sscanf
	.section	___ksymtab+rkos_memchr,"a"
	.align	2
	.type	__ksymtab_rkos_memchr, %object
	.size	__ksymtab_rkos_memchr, 12
__ksymtab_rkos_memchr:
	.word	rkos_memchr
	.word	__kstrtab_rkos_memchr
	.word	__kstrtabns_rkos_memchr
	.section	___ksymtab+rkos_memchr_inv,"a"
	.align	2
	.type	__ksymtab_rkos_memchr_inv, %object
	.size	__ksymtab_rkos_memchr_inv, 12
__ksymtab_rkos_memchr_inv:
	.word	rkos_memchr_inv
	.word	__kstrtab_rkos_memchr_inv
	.word	__kstrtabns_rkos_memchr_inv
	.section	___ksymtab+rkos_memcmp,"a"
	.align	2
	.type	__ksymtab_rkos_memcmp, %object
	.size	__ksymtab_rkos_memcmp, 12
__ksymtab_rkos_memcmp:
	.word	rkos_memcmp
	.word	__kstrtab_rkos_memcmp
	.word	__kstrtabns_rkos_memcmp
	.section	___ksymtab+rkos_memcpy,"a"
	.align	2
	.type	__ksymtab_rkos_memcpy, %object
	.size	__ksymtab_rkos_memcpy, 12
__ksymtab_rkos_memcpy:
	.word	rkos_memcpy
	.word	__kstrtab_rkos_memcpy
	.word	__kstrtabns_rkos_memcpy
	.section	___ksymtab+rkos_memmove,"a"
	.align	2
	.type	__ksymtab_rkos_memmove, %object
	.size	__ksymtab_rkos_memmove, 12
__ksymtab_rkos_memmove:
	.word	rkos_memmove
	.word	__kstrtab_rkos_memmove
	.word	__kstrtabns_rkos_memmove
	.section	___ksymtab+rkos_memscan,"a"
	.align	2
	.type	__ksymtab_rkos_memscan, %object
	.size	__ksymtab_rkos_memscan, 12
__ksymtab_rkos_memscan:
	.word	rkos_memscan
	.word	__kstrtab_rkos_memscan
	.word	__kstrtabns_rkos_memscan
	.section	___ksymtab+rkos_memset,"a"
	.align	2
	.type	__ksymtab_rkos_memset, %object
	.size	__ksymtab_rkos_memset, 12
__ksymtab_rkos_memset:
	.word	rkos_memset
	.word	__kstrtab_rkos_memset
	.word	__kstrtabns_rkos_memset
	.section	___ksymtab+rkos_scnprintf,"a"
	.align	2
	.type	__ksymtab_rkos_scnprintf, %object
	.size	__ksymtab_rkos_scnprintf, 12
__ksymtab_rkos_scnprintf:
	.word	rkos_scnprintf
	.word	__kstrtab_rkos_scnprintf
	.word	__kstrtabns_rkos_scnprintf
	.section	___ksymtab+rkos_snprintf,"a"
	.align	2
	.type	__ksymtab_rkos_snprintf, %object
	.size	__ksymtab_rkos_snprintf, 12
__ksymtab_rkos_snprintf:
	.word	rkos_snprintf
	.word	__kstrtab_rkos_snprintf
	.word	__kstrtabns_rkos_snprintf
	.section	___ksymtab+rkos_sprintf,"a"
	.align	2
	.type	__ksymtab_rkos_sprintf, %object
	.size	__ksymtab_rkos_sprintf, 12
__ksymtab_rkos_sprintf:
	.word	rkos_sprintf
	.word	__kstrtab_rkos_sprintf
	.word	__kstrtabns_rkos_sprintf
	.section	___ksymtab+rkos_sscanf,"a"
	.align	2
	.type	__ksymtab_rkos_sscanf, %object
	.size	__ksymtab_rkos_sscanf, 12
__ksymtab_rkos_sscanf:
	.word	rkos_sscanf
	.word	__kstrtab_rkos_sscanf
	.word	__kstrtabns_rkos_sscanf
	.section	___ksymtab+rkos_strcasecmp,"a"
	.align	2
	.type	__ksymtab_rkos_strcasecmp, %object
	.size	__ksymtab_rkos_strcasecmp, 12
__ksymtab_rkos_strcasecmp:
	.word	rkos_strcasecmp
	.word	__kstrtab_rkos_strcasecmp
	.word	__kstrtabns_rkos_strcasecmp
	.section	___ksymtab+rkos_strcat,"a"
	.align	2
	.type	__ksymtab_rkos_strcat, %object
	.size	__ksymtab_rkos_strcat, 12
__ksymtab_rkos_strcat:
	.word	rkos_strcat
	.word	__kstrtab_rkos_strcat
	.word	__kstrtabns_rkos_strcat
	.section	___ksymtab+rkos_strchr,"a"
	.align	2
	.type	__ksymtab_rkos_strchr, %object
	.size	__ksymtab_rkos_strchr, 12
__ksymtab_rkos_strchr:
	.word	rkos_strchr
	.word	__kstrtab_rkos_strchr
	.word	__kstrtabns_rkos_strchr
	.section	___ksymtab+rkos_strcmp,"a"
	.align	2
	.type	__ksymtab_rkos_strcmp, %object
	.size	__ksymtab_rkos_strcmp, 12
__ksymtab_rkos_strcmp:
	.word	rkos_strcmp
	.word	__kstrtab_rkos_strcmp
	.word	__kstrtabns_rkos_strcmp
	.section	___ksymtab+rkos_strcpy,"a"
	.align	2
	.type	__ksymtab_rkos_strcpy, %object
	.size	__ksymtab_rkos_strcpy, 12
__ksymtab_rkos_strcpy:
	.word	rkos_strcpy
	.word	__kstrtab_rkos_strcpy
	.word	__kstrtabns_rkos_strcpy
	.section	___ksymtab+rkos_strcspn,"a"
	.align	2
	.type	__ksymtab_rkos_strcspn, %object
	.size	__ksymtab_rkos_strcspn, 12
__ksymtab_rkos_strcspn:
	.word	rkos_strcspn
	.word	__kstrtab_rkos_strcspn
	.word	__kstrtabns_rkos_strcspn
	.section	___ksymtab+rkos_strlcat,"a"
	.align	2
	.type	__ksymtab_rkos_strlcat, %object
	.size	__ksymtab_rkos_strlcat, 12
__ksymtab_rkos_strlcat:
	.word	rkos_strlcat
	.word	__kstrtab_rkos_strlcat
	.word	__kstrtabns_rkos_strlcat
	.section	___ksymtab+rkos_strlcpy,"a"
	.align	2
	.type	__ksymtab_rkos_strlcpy, %object
	.size	__ksymtab_rkos_strlcpy, 12
__ksymtab_rkos_strlcpy:
	.word	rkos_strlcpy
	.word	__kstrtab_rkos_strlcpy
	.word	__kstrtabns_rkos_strlcpy
	.section	___ksymtab+rkos_strlen,"a"
	.align	2
	.type	__ksymtab_rkos_strlen, %object
	.size	__ksymtab_rkos_strlen, 12
__ksymtab_rkos_strlen:
	.word	rkos_strlen
	.word	__kstrtab_rkos_strlen
	.word	__kstrtabns_rkos_strlen
	.section	___ksymtab+rkos_strncasecmp,"a"
	.align	2
	.type	__ksymtab_rkos_strncasecmp, %object
	.size	__ksymtab_rkos_strncasecmp, 12
__ksymtab_rkos_strncasecmp:
	.word	rkos_strncasecmp
	.word	__kstrtab_rkos_strncasecmp
	.word	__kstrtabns_rkos_strncasecmp
	.section	___ksymtab+rkos_strncat,"a"
	.align	2
	.type	__ksymtab_rkos_strncat, %object
	.size	__ksymtab_rkos_strncat, 12
__ksymtab_rkos_strncat:
	.word	rkos_strncat
	.word	__kstrtab_rkos_strncat
	.word	__kstrtabns_rkos_strncat
	.section	___ksymtab+rkos_strnchr,"a"
	.align	2
	.type	__ksymtab_rkos_strnchr, %object
	.size	__ksymtab_rkos_strnchr, 12
__ksymtab_rkos_strnchr:
	.word	rkos_strnchr
	.word	__kstrtab_rkos_strnchr
	.word	__kstrtabns_rkos_strnchr
	.section	___ksymtab+rkos_strncmp,"a"
	.align	2
	.type	__ksymtab_rkos_strncmp, %object
	.size	__ksymtab_rkos_strncmp, 12
__ksymtab_rkos_strncmp:
	.word	rkos_strncmp
	.word	__kstrtab_rkos_strncmp
	.word	__kstrtabns_rkos_strncmp
	.section	___ksymtab+rkos_strncpy,"a"
	.align	2
	.type	__ksymtab_rkos_strncpy, %object
	.size	__ksymtab_rkos_strncpy, 12
__ksymtab_rkos_strncpy:
	.word	rkos_strncpy
	.word	__kstrtab_rkos_strncpy
	.word	__kstrtabns_rkos_strncpy
	.section	___ksymtab+rkos_strnicmp,"a"
	.align	2
	.type	__ksymtab_rkos_strnicmp, %object
	.size	__ksymtab_rkos_strnicmp, 12
__ksymtab_rkos_strnicmp:
	.word	rkos_strnicmp
	.word	__kstrtab_rkos_strnicmp
	.word	__kstrtabns_rkos_strnicmp
	.section	___ksymtab+rkos_strnlen,"a"
	.align	2
	.type	__ksymtab_rkos_strnlen, %object
	.size	__ksymtab_rkos_strnlen, 12
__ksymtab_rkos_strnlen:
	.word	rkos_strnlen
	.word	__kstrtab_rkos_strnlen
	.word	__kstrtabns_rkos_strnlen
	.section	___ksymtab+rkos_strnstr,"a"
	.align	2
	.type	__ksymtab_rkos_strnstr, %object
	.size	__ksymtab_rkos_strnstr, 12
__ksymtab_rkos_strnstr:
	.word	rkos_strnstr
	.word	__kstrtab_rkos_strnstr
	.word	__kstrtabns_rkos_strnstr
	.section	___ksymtab+rkos_strpbrk,"a"
	.align	2
	.type	__ksymtab_rkos_strpbrk, %object
	.size	__ksymtab_rkos_strpbrk, 12
__ksymtab_rkos_strpbrk:
	.word	rkos_strpbrk
	.word	__kstrtab_rkos_strpbrk
	.word	__kstrtabns_rkos_strpbrk
	.section	___ksymtab+rkos_strrchr,"a"
	.align	2
	.type	__ksymtab_rkos_strrchr, %object
	.size	__ksymtab_rkos_strrchr, 12
__ksymtab_rkos_strrchr:
	.word	rkos_strrchr
	.word	__kstrtab_rkos_strrchr
	.word	__kstrtabns_rkos_strrchr
	.section	___ksymtab+rkos_strsep,"a"
	.align	2
	.type	__ksymtab_rkos_strsep, %object
	.size	__ksymtab_rkos_strsep, 12
__ksymtab_rkos_strsep:
	.word	rkos_strsep
	.word	__kstrtab_rkos_strsep
	.word	__kstrtabns_rkos_strsep
	.section	___ksymtab+rkos_strspn,"a"
	.align	2
	.type	__ksymtab_rkos_strspn, %object
	.size	__ksymtab_rkos_strspn, 12
__ksymtab_rkos_strspn:
	.word	rkos_strspn
	.word	__kstrtab_rkos_strspn
	.word	__kstrtabns_rkos_strspn
	.section	___ksymtab+rkos_strstr,"a"
	.align	2
	.type	__ksymtab_rkos_strstr, %object
	.size	__ksymtab_rkos_strstr, 12
__ksymtab_rkos_strstr:
	.word	rkos_strstr
	.word	__kstrtab_rkos_strstr
	.word	__kstrtabns_rkos_strstr
	.section	___ksymtab+rkos_strtol,"a"
	.align	2
	.type	__ksymtab_rkos_strtol, %object
	.size	__ksymtab_rkos_strtol, 12
__ksymtab_rkos_strtol:
	.word	rkos_strtol
	.word	__kstrtab_rkos_strtol
	.word	__kstrtabns_rkos_strtol
	.section	___ksymtab+rkos_strtoll,"a"
	.align	2
	.type	__ksymtab_rkos_strtoll, %object
	.size	__ksymtab_rkos_strtoll, 12
__ksymtab_rkos_strtoll:
	.word	rkos_strtoll
	.word	__kstrtab_rkos_strtoll
	.word	__kstrtabns_rkos_strtoll
	.section	___ksymtab+rkos_strtoul,"a"
	.align	2
	.type	__ksymtab_rkos_strtoul, %object
	.size	__ksymtab_rkos_strtoul, 12
__ksymtab_rkos_strtoul:
	.word	rkos_strtoul
	.word	__kstrtab_rkos_strtoul
	.word	__kstrtabns_rkos_strtoul
	.section	___ksymtab+rkos_strtoull,"a"
	.align	2
	.type	__ksymtab_rkos_strtoull, %object
	.size	__ksymtab_rkos_strtoull, 12
__ksymtab_rkos_strtoull:
	.word	rkos_strtoull
	.word	__kstrtab_rkos_strtoull
	.word	__kstrtabns_rkos_strtoull
	.ident	"GCC: (crosstool-NG 1.24.0 - v1.0.50) 8.3.0"
	.section	.note.GNU-stack,"",%progbits
